/*
 *  AKAP79_gvf.h
 *
 *  GSL C prototype file for the functions defined in AKAP79_gvf.c
 *
 *  This file was generated by the program VFGEN, version: 2.6.0.dev1
 *  Generated on 28-Jan-2022 at 09:23
 */

int AKAP79_vf(double, const double [], double [], void *);
int AKAP79_jac(double, const double [], double *, double *, void *);
int AKAP79_jacp(double, const double [], double *, void *);
