#
# AKAP79.R
#
# R vector field functions for: AKAP79
#
# This file was generated by the program VFGEN, version: 2.6.0.dev1
# Generated on 28-Jan-2022 at 09:23
#


#
# AKAP79(t, state, parameters)
#
# The vector field function
#
AKAP79 <- function(t, state, parameters) {
    Rii        <- state[1]
    cAMP       <- state[2]
    RiiP       <- state[3]
    Rii_C      <- state[4]
    RiiP_cAMP  <- state[5]
    RiiP_C     <- state[6]
    RiiP_C_cAMP <- state[7]
    C          <- state[8]
    Rii_cAMP   <- state[9]
    Rii_C_cAMP <- state[10]
    CaN        <- state[11]
    RiiP_CaN   <- state[12]
    RiiP_cAMP_CaN <- state[13]
    AKAR4      <- state[14]
    AKAR4_C    <- state[15]
    AKAR4p     <- state[16]
    kf_Rii_C__RiiP_C <- parameters[1]
    kf_RiiP_CxcAMP__RiiP_C_cAMP <- parameters[2]
    kf_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[3]
    kb_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[4]
    kb_RiiPXcAMP__RiiP_cAMP <- parameters[5]
    kf_RiiPXcAMP__RiiP_cAMP <- parameters[6]
    kf_RiiPxC__RiiP_C <- parameters[7]
    kb_RiiPxC__RiiP_C <- parameters[8]
    kf_cAMPxRii__Rii_cAMP <- parameters[9]
    kb_cAMPxRii__Rii_cAMP <- parameters[10]
    kf_Rii_CxcAMP__Rii_C_cAMP <- parameters[11]
    kb_Rii_CxcAMP__Rii_C_cAMP <- parameters[12]
    kf_RiixC__Rii_C <- parameters[13]
    kf_Rii_cAMPxC__Rii_C_cAMP <- parameters[14]
    kb_Rii_cAMPxC__Rii_C_cAMP <- parameters[15]
    kf_Rii_C_cAMP__RiiP_C_cAMP <- parameters[16]
    kb_RiixC__Rii_C <- parameters[17]
    AKAPoff_1  <- parameters[18]
    AKAPoff_3  <- parameters[19]
    AKAPon_1   <- parameters[20]
    AKAPon_3   <- parameters[21]
    kf_C_AKAR4 <- parameters[22]
    kb_C_AKAR4 <- parameters[23]
    kcat_AKARp <- parameters[24]
    kmOFF      <- parameters[25]
    kmON       <- parameters[26]
    KD_T       <- parameters[27]
    b_AKAP     <- parameters[28]

    kf_RiiP_cAMP_CaN__CaNXRii_cAMP <- AKAPon_1*b_AKAP-(-1+b_AKAP)*AKAPoff_1;
    kb_RiiPxCaN__RiiP_CaN <- -(-1+b_AKAP)*AKAPoff_3+b_AKAP*AKAPon_3;
    kf_RiiP_CaN__RiixCaN <- AKAPon_1*b_AKAP-(-1+b_AKAP)*AKAPoff_1;
    kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -(-1+b_AKAP)*AKAPoff_3+b_AKAP*AKAPon_3;
    kf_RiiPxCaN__RiiP_CaN <- -(-1+b_AKAP)*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*kmOFF^(-1)+kmON^(-1)*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*b_AKAP;
    kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -(-1+b_AKAP)*(kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN+kf_RiiP_CaN__RiixCaN)*kmOFF^(-1)+kmON^(-1)*(kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN+kf_RiiP_CaN__RiixCaN)*b_AKAP;
    kb_RiiP_CxcAMP__RiiP_C_cAMP <- kf_RiiP_CxcAMP__RiiP_C_cAMP*KD_T;
    reaction_51 <- Rii_C*kf_Rii_C__RiiP_C;
    reaction_14 <- -RiiP_C*kb_RiiPxC__RiiP_C+kf_RiiPxC__RiiP_C*RiiP*C;
    reaction_12 <- -kb_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C_cAMP+RiiP_C*cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP;
    reaction_43 <- RiiP*kf_RiiPXcAMP__RiiP_cAMP*cAMP-RiiP_cAMP*kb_RiiPXcAMP__RiiP_cAMP;
    reaction_23 <- kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP*C-RiiP_C_cAMP*kb_RiiP_cAMPxC__RiiP_C_cAMP;
    reaction_78 <- kf_cAMPxRii__Rii_cAMP*cAMP*Rii-kb_cAMPxRii__Rii_cAMP*Rii_cAMP;
    reaction_56 <- kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C*cAMP-Rii_C_cAMP*kb_Rii_CxcAMP__Rii_C_cAMP;
    reaction_76 <- kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP*C-Rii_C_cAMP*kb_Rii_cAMPxC__Rii_C_cAMP;
    reaction_62 <- Rii_C_cAMP*kf_Rii_C_cAMP__RiiP_C_cAMP;
    reaction_58 <- -Rii_C*kb_RiixC__Rii_C+kf_RiixC__Rii_C*C*Rii;
    reaction_44_ <- RiiP*kf_RiiPxCaN__RiiP_CaN*CaN-RiiP_CaN*kb_RiiPxCaN__RiiP_CaN;
    reaction_33_ <- -kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP_CaN+kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP*CaN;
    reaction_4_8 <- kf_RiiP_CaN__RiixCaN*RiiP_CaN;
    reaction_3_7 <- RiiP_cAMP_CaN*kf_RiiP_cAMP_CaN__CaNXRii_cAMP;
    reaction_1 <- kf_C_AKAR4*C*AKAR4-kb_C_AKAR4*AKAR4_C;
    reaction_2 <- AKAR4_C*kcat_AKARp;
    vf_ <- vector(len = 16)
    vf_[1] = -reaction_78-reaction_58+reaction_4_8;
    vf_[2] = -reaction_12-reaction_78-reaction_43-reaction_56;
    vf_[3] = -reaction_14-reaction_44_-reaction_43;
    vf_[4] = -reaction_51-reaction_56+reaction_58;
    vf_[5] = -reaction_33_-reaction_23+reaction_43;
    vf_[6] = -reaction_12+reaction_14+reaction_51;
    vf_[7] = reaction_12+reaction_62+reaction_23;
    vf_[8] = reaction_2-reaction_1-reaction_14-reaction_23-reaction_76-reaction_58;
    vf_[9] = reaction_78-reaction_76+reaction_3_7;
    vf_[10] = -reaction_62+reaction_76+reaction_56;
    vf_[11] = -reaction_33_-reaction_44_+reaction_3_7+reaction_4_8;
    vf_[12] = reaction_44_-reaction_4_8;
    vf_[13] = reaction_33_-reaction_3_7;
    vf_[14] = -reaction_1;
    vf_[15] = -reaction_2+reaction_1;
    vf_[16] = reaction_2;
    return(list(vf_))
}

#
# AKAP79_jac(t, state, parameters)
#
# The jacobian function
#
AKAP79_jac <- function(t, state, parameters) {
    Rii        <- state[1]
    cAMP       <- state[2]
    RiiP       <- state[3]
    Rii_C      <- state[4]
    RiiP_cAMP  <- state[5]
    RiiP_C     <- state[6]
    RiiP_C_cAMP <- state[7]
    C          <- state[8]
    Rii_cAMP   <- state[9]
    Rii_C_cAMP <- state[10]
    CaN        <- state[11]
    RiiP_CaN   <- state[12]
    RiiP_cAMP_CaN <- state[13]
    AKAR4      <- state[14]
    AKAR4_C    <- state[15]
    AKAR4p     <- state[16]
    kf_Rii_C__RiiP_C <- parameters[1]
    kf_RiiP_CxcAMP__RiiP_C_cAMP <- parameters[2]
    kf_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[3]
    kb_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[4]
    kb_RiiPXcAMP__RiiP_cAMP <- parameters[5]
    kf_RiiPXcAMP__RiiP_cAMP <- parameters[6]
    kf_RiiPxC__RiiP_C <- parameters[7]
    kb_RiiPxC__RiiP_C <- parameters[8]
    kf_cAMPxRii__Rii_cAMP <- parameters[9]
    kb_cAMPxRii__Rii_cAMP <- parameters[10]
    kf_Rii_CxcAMP__Rii_C_cAMP <- parameters[11]
    kb_Rii_CxcAMP__Rii_C_cAMP <- parameters[12]
    kf_RiixC__Rii_C <- parameters[13]
    kf_Rii_cAMPxC__Rii_C_cAMP <- parameters[14]
    kb_Rii_cAMPxC__Rii_C_cAMP <- parameters[15]
    kf_Rii_C_cAMP__RiiP_C_cAMP <- parameters[16]
    kb_RiixC__Rii_C <- parameters[17]
    AKAPoff_1  <- parameters[18]
    AKAPoff_3  <- parameters[19]
    AKAPon_1   <- parameters[20]
    AKAPon_3   <- parameters[21]
    kf_C_AKAR4 <- parameters[22]
    kb_C_AKAR4 <- parameters[23]
    kcat_AKARp <- parameters[24]
    kmOFF      <- parameters[25]
    kmON       <- parameters[26]
    KD_T       <- parameters[27]
    b_AKAP     <- parameters[28]
    jac_ = matrix(nrow = 16, ncol = 16)
    jac_[1,1] = -kf_RiixC__Rii_C*C-kf_cAMPxRii__Rii_cAMP*cAMP
    jac_[1,2] = -kf_cAMPxRii__Rii_cAMP*Rii
    jac_[1,3] = 0
    jac_[1,4] = kb_RiixC__Rii_C
    jac_[1,5] = 0
    jac_[1,6] = 0
    jac_[1,7] = 0
    jac_[1,8] = -kf_RiixC__Rii_C*Rii
    jac_[1,9] = kb_cAMPxRii__Rii_cAMP
    jac_[1,10] = 0
    jac_[1,11] = 0
    jac_[1,12] = AKAPon_1*b_AKAP-(-1+b_AKAP)*AKAPoff_1
    jac_[1,13] = 0
    jac_[1,14] = 0
    jac_[1,15] = 0
    jac_[1,16] = 0
    jac_[2,1] = -kf_cAMPxRii__Rii_cAMP*cAMP
    jac_[2,2] = -kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C-kf_cAMPxRii__Rii_cAMP*Rii-RiiP_C*kf_RiiP_CxcAMP__RiiP_C_cAMP-RiiP*kf_RiiPXcAMP__RiiP_cAMP
    jac_[2,3] = -kf_RiiPXcAMP__RiiP_cAMP*cAMP
    jac_[2,4] = -kf_Rii_CxcAMP__Rii_C_cAMP*cAMP
    jac_[2,5] = kb_RiiPXcAMP__RiiP_cAMP
    jac_[2,6] = -cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[2,7] = kf_RiiP_CxcAMP__RiiP_C_cAMP*KD_T
    jac_[2,8] = 0
    jac_[2,9] = kb_cAMPxRii__Rii_cAMP
    jac_[2,10] = kb_Rii_CxcAMP__Rii_C_cAMP
    jac_[2,11] = 0
    jac_[2,12] = 0
    jac_[2,13] = 0
    jac_[2,14] = 0
    jac_[2,15] = 0
    jac_[2,16] = 0
    jac_[3,1] = 0
    jac_[3,2] = -RiiP*kf_RiiPXcAMP__RiiP_cAMP
    jac_[3,3] = -kf_RiiPXcAMP__RiiP_cAMP*cAMP-CaN*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)-kf_RiiPxC__RiiP_C*C
    jac_[3,4] = 0
    jac_[3,5] = kb_RiiPXcAMP__RiiP_cAMP
    jac_[3,6] = kb_RiiPxC__RiiP_C
    jac_[3,7] = 0
    jac_[3,8] = -kf_RiiPxC__RiiP_C*RiiP
    jac_[3,9] = 0
    jac_[3,10] = 0
    jac_[3,11] = -RiiP*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)
    jac_[3,12] = -(-1+b_AKAP)*AKAPoff_3+b_AKAP*AKAPon_3
    jac_[3,13] = 0
    jac_[3,14] = 0
    jac_[3,15] = 0
    jac_[3,16] = 0
    jac_[4,1] = kf_RiixC__Rii_C*C
    jac_[4,2] = -kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C
    jac_[4,3] = 0
    jac_[4,4] = -kb_RiixC__Rii_C-kf_Rii_C__RiiP_C-kf_Rii_CxcAMP__Rii_C_cAMP*cAMP
    jac_[4,5] = 0
    jac_[4,6] = 0
    jac_[4,7] = 0
    jac_[4,8] = kf_RiixC__Rii_C*Rii
    jac_[4,9] = 0
    jac_[4,10] = kb_Rii_CxcAMP__Rii_C_cAMP
    jac_[4,11] = 0
    jac_[4,12] = 0
    jac_[4,13] = 0
    jac_[4,14] = 0
    jac_[4,15] = 0
    jac_[4,16] = 0
    jac_[5,1] = 0
    jac_[5,2] = RiiP*kf_RiiPXcAMP__RiiP_cAMP
    jac_[5,3] = kf_RiiPXcAMP__RiiP_cAMP*cAMP
    jac_[5,4] = 0
    jac_[5,5] = -CaN*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)-kf_RiiP_cAMPxC__RiiP_C_cAMP*C-kb_RiiPXcAMP__RiiP_cAMP
    jac_[5,6] = 0
    jac_[5,7] = kb_RiiP_cAMPxC__RiiP_C_cAMP
    jac_[5,8] = -kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP
    jac_[5,9] = 0
    jac_[5,10] = 0
    jac_[5,11] = -RiiP_cAMP*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)
    jac_[5,12] = 0
    jac_[5,13] = -(-1+b_AKAP)*AKAPoff_3+b_AKAP*AKAPon_3
    jac_[5,14] = 0
    jac_[5,15] = 0
    jac_[5,16] = 0
    jac_[6,1] = 0
    jac_[6,2] = -RiiP_C*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[6,3] = kf_RiiPxC__RiiP_C*C
    jac_[6,4] = kf_Rii_C__RiiP_C
    jac_[6,5] = 0
    jac_[6,6] = -cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP-kb_RiiPxC__RiiP_C
    jac_[6,7] = kf_RiiP_CxcAMP__RiiP_C_cAMP*KD_T
    jac_[6,8] = kf_RiiPxC__RiiP_C*RiiP
    jac_[6,9] = 0
    jac_[6,10] = 0
    jac_[6,11] = 0
    jac_[6,12] = 0
    jac_[6,13] = 0
    jac_[6,14] = 0
    jac_[6,15] = 0
    jac_[6,16] = 0
    jac_[7,1] = 0
    jac_[7,2] = RiiP_C*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[7,3] = 0
    jac_[7,4] = 0
    jac_[7,5] = kf_RiiP_cAMPxC__RiiP_C_cAMP*C
    jac_[7,6] = cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[7,7] = -kb_RiiP_cAMPxC__RiiP_C_cAMP-kf_RiiP_CxcAMP__RiiP_C_cAMP*KD_T
    jac_[7,8] = kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP
    jac_[7,9] = 0
    jac_[7,10] = kf_Rii_C_cAMP__RiiP_C_cAMP
    jac_[7,11] = 0
    jac_[7,12] = 0
    jac_[7,13] = 0
    jac_[7,14] = 0
    jac_[7,15] = 0
    jac_[7,16] = 0
    jac_[8,1] = -kf_RiixC__Rii_C*C
    jac_[8,2] = 0
    jac_[8,3] = -kf_RiiPxC__RiiP_C*C
    jac_[8,4] = kb_RiixC__Rii_C
    jac_[8,5] = -kf_RiiP_cAMPxC__RiiP_C_cAMP*C
    jac_[8,6] = kb_RiiPxC__RiiP_C
    jac_[8,7] = kb_RiiP_cAMPxC__RiiP_C_cAMP
    jac_[8,8] = -kf_RiixC__Rii_C*Rii-kf_C_AKAR4*AKAR4-kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP-kf_RiiPxC__RiiP_C*RiiP-kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP
    jac_[8,9] = -kf_Rii_cAMPxC__Rii_C_cAMP*C
    jac_[8,10] = kb_Rii_cAMPxC__Rii_C_cAMP
    jac_[8,11] = 0
    jac_[8,12] = 0
    jac_[8,13] = 0
    jac_[8,14] = -kf_C_AKAR4*C
    jac_[8,15] = kb_C_AKAR4+kcat_AKARp
    jac_[8,16] = 0
    jac_[9,1] = kf_cAMPxRii__Rii_cAMP*cAMP
    jac_[9,2] = kf_cAMPxRii__Rii_cAMP*Rii
    jac_[9,3] = 0
    jac_[9,4] = 0
    jac_[9,5] = 0
    jac_[9,6] = 0
    jac_[9,7] = 0
    jac_[9,8] = -kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP
    jac_[9,9] = -kb_cAMPxRii__Rii_cAMP-kf_Rii_cAMPxC__Rii_C_cAMP*C
    jac_[9,10] = kb_Rii_cAMPxC__Rii_C_cAMP
    jac_[9,11] = 0
    jac_[9,12] = 0
    jac_[9,13] = AKAPon_1*b_AKAP-(-1+b_AKAP)*AKAPoff_1
    jac_[9,14] = 0
    jac_[9,15] = 0
    jac_[9,16] = 0
    jac_[10,1] = 0
    jac_[10,2] = kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C
    jac_[10,3] = 0
    jac_[10,4] = kf_Rii_CxcAMP__Rii_C_cAMP*cAMP
    jac_[10,5] = 0
    jac_[10,6] = 0
    jac_[10,7] = 0
    jac_[10,8] = kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP
    jac_[10,9] = kf_Rii_cAMPxC__Rii_C_cAMP*C
    jac_[10,10] = -kf_Rii_C_cAMP__RiiP_C_cAMP-kb_Rii_CxcAMP__Rii_C_cAMP-kb_Rii_cAMPxC__Rii_C_cAMP
    jac_[10,11] = 0
    jac_[10,12] = 0
    jac_[10,13] = 0
    jac_[10,14] = 0
    jac_[10,15] = 0
    jac_[10,16] = 0
    jac_[11,1] = 0
    jac_[11,2] = 0
    jac_[11,3] = -CaN*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)
    jac_[11,4] = 0
    jac_[11,5] = -CaN*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)
    jac_[11,6] = 0
    jac_[11,7] = 0
    jac_[11,8] = 0
    jac_[11,9] = 0
    jac_[11,10] = 0
    jac_[11,11] = -RiiP*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)-RiiP_cAMP*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)
    jac_[11,12] = -(-1+b_AKAP)*AKAPoff_3+b_AKAP*AKAPon_3+AKAPon_1*b_AKAP-(-1+b_AKAP)*AKAPoff_1
    jac_[11,13] = -(-1+b_AKAP)*AKAPoff_3+b_AKAP*AKAPon_3+AKAPon_1*b_AKAP-(-1+b_AKAP)*AKAPoff_1
    jac_[11,14] = 0
    jac_[11,15] = 0
    jac_[11,16] = 0
    jac_[12,1] = 0
    jac_[12,2] = 0
    jac_[12,3] = CaN*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)
    jac_[12,4] = 0
    jac_[12,5] = 0
    jac_[12,6] = 0
    jac_[12,7] = 0
    jac_[12,8] = 0
    jac_[12,9] = 0
    jac_[12,10] = 0
    jac_[12,11] = RiiP*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)
    jac_[12,12] = (-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1
    jac_[12,13] = 0
    jac_[12,14] = 0
    jac_[12,15] = 0
    jac_[12,16] = 0
    jac_[13,1] = 0
    jac_[13,2] = 0
    jac_[13,3] = 0
    jac_[13,4] = 0
    jac_[13,5] = CaN*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)
    jac_[13,6] = 0
    jac_[13,7] = 0
    jac_[13,8] = 0
    jac_[13,9] = 0
    jac_[13,10] = 0
    jac_[13,11] = RiiP_cAMP*((-1+b_AKAP)*((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmOFF^(-1)-((-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1)*kmON^(-1)*b_AKAP)
    jac_[13,12] = 0
    jac_[13,13] = (-1+b_AKAP)*AKAPoff_3-b_AKAP*AKAPon_3-AKAPon_1*b_AKAP+(-1+b_AKAP)*AKAPoff_1
    jac_[13,14] = 0
    jac_[13,15] = 0
    jac_[13,16] = 0
    jac_[14,1] = 0
    jac_[14,2] = 0
    jac_[14,3] = 0
    jac_[14,4] = 0
    jac_[14,5] = 0
    jac_[14,6] = 0
    jac_[14,7] = 0
    jac_[14,8] = -kf_C_AKAR4*AKAR4
    jac_[14,9] = 0
    jac_[14,10] = 0
    jac_[14,11] = 0
    jac_[14,12] = 0
    jac_[14,13] = 0
    jac_[14,14] = -kf_C_AKAR4*C
    jac_[14,15] = kb_C_AKAR4
    jac_[14,16] = 0
    jac_[15,1] = 0
    jac_[15,2] = 0
    jac_[15,3] = 0
    jac_[15,4] = 0
    jac_[15,5] = 0
    jac_[15,6] = 0
    jac_[15,7] = 0
    jac_[15,8] = kf_C_AKAR4*AKAR4
    jac_[15,9] = 0
    jac_[15,10] = 0
    jac_[15,11] = 0
    jac_[15,12] = 0
    jac_[15,13] = 0
    jac_[15,14] = kf_C_AKAR4*C
    jac_[15,15] = -kb_C_AKAR4-kcat_AKARp
    jac_[15,16] = 0
    jac_[16,1] = 0
    jac_[16,2] = 0
    jac_[16,3] = 0
    jac_[16,4] = 0
    jac_[16,5] = 0
    jac_[16,6] = 0
    jac_[16,7] = 0
    jac_[16,8] = 0
    jac_[16,9] = 0
    jac_[16,10] = 0
    jac_[16,11] = 0
    jac_[16,12] = 0
    jac_[16,13] = 0
    jac_[16,14] = 0
    jac_[16,15] = kcat_AKARp
    jac_[16,16] = 0
    return(jac_)
}


#
# AKAP79_sol_AKAR4pOUT
#
# This function implements the user-defined function "AKAR4pOUT"
#
AKAP79_sol_AKAR4pOUT <- function(sol, parameters) {
    t <- sol[, 1]
    Rii        <- sol[, 2]
    cAMP       <- sol[, 3]
    RiiP       <- sol[, 4]
    Rii_C      <- sol[, 5]
    RiiP_cAMP  <- sol[, 6]
    RiiP_C     <- sol[, 7]
    RiiP_C_cAMP <- sol[, 8]
    C          <- sol[, 9]
    Rii_cAMP   <- sol[, 10]
    Rii_C_cAMP <- sol[, 11]
    CaN        <- sol[, 12]
    RiiP_CaN   <- sol[, 13]
    RiiP_cAMP_CaN <- sol[, 14]
    AKAR4      <- sol[, 15]
    AKAR4_C    <- sol[, 16]
    AKAR4p     <- sol[, 17]
    kf_Rii_C__RiiP_C <- parameters[1]
    kf_RiiP_CxcAMP__RiiP_C_cAMP <- parameters[2]
    kf_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[3]
    kb_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[4]
    kb_RiiPXcAMP__RiiP_cAMP <- parameters[5]
    kf_RiiPXcAMP__RiiP_cAMP <- parameters[6]
    kf_RiiPxC__RiiP_C <- parameters[7]
    kb_RiiPxC__RiiP_C <- parameters[8]
    kf_cAMPxRii__Rii_cAMP <- parameters[9]
    kb_cAMPxRii__Rii_cAMP <- parameters[10]
    kf_Rii_CxcAMP__Rii_C_cAMP <- parameters[11]
    kb_Rii_CxcAMP__Rii_C_cAMP <- parameters[12]
    kf_RiixC__Rii_C <- parameters[13]
    kf_Rii_cAMPxC__Rii_C_cAMP <- parameters[14]
    kb_Rii_cAMPxC__Rii_C_cAMP <- parameters[15]
    kf_Rii_C_cAMP__RiiP_C_cAMP <- parameters[16]
    kb_RiixC__Rii_C <- parameters[17]
    AKAPoff_1  <- parameters[18]
    AKAPoff_3  <- parameters[19]
    AKAPon_1   <- parameters[20]
    AKAPon_3   <- parameters[21]
    kf_C_AKAR4 <- parameters[22]
    kb_C_AKAR4 <- parameters[23]
    kcat_AKARp <- parameters[24]
    kmOFF      <- parameters[25]
    kmON       <- parameters[26]
    KD_T       <- parameters[27]
    b_AKAP     <- parameters[28]
    kf_RiiP_cAMP_CaN__CaNXRii_cAMP <- AKAPon_1*b_AKAP-(-1+b_AKAP)*AKAPoff_1
    kb_RiiPxCaN__RiiP_CaN <- -(-1+b_AKAP)*AKAPoff_3+b_AKAP*AKAPon_3
    kf_RiiP_CaN__RiixCaN <- AKAPon_1*b_AKAP-(-1+b_AKAP)*AKAPoff_1
    kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -(-1+b_AKAP)*AKAPoff_3+b_AKAP*AKAPon_3
    kf_RiiPxCaN__RiiP_CaN <- -(-1+b_AKAP)*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*kmOFF^(-1)+kmON^(-1)*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*b_AKAP
    kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -(-1+b_AKAP)*(kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN+kf_RiiP_CaN__RiixCaN)*kmOFF^(-1)+kmON^(-1)*(kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN+kf_RiiP_CaN__RiixCaN)*b_AKAP
    kb_RiiP_CxcAMP__RiiP_C_cAMP <- kf_RiiP_CxcAMP__RiiP_C_cAMP*KD_T
    reaction_51 <- Rii_C*kf_Rii_C__RiiP_C
    reaction_14 <- -RiiP_C*kb_RiiPxC__RiiP_C+kf_RiiPxC__RiiP_C*RiiP*C
    reaction_12 <- -kb_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C_cAMP+RiiP_C*cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP
    reaction_43 <- RiiP*kf_RiiPXcAMP__RiiP_cAMP*cAMP-RiiP_cAMP*kb_RiiPXcAMP__RiiP_cAMP
    reaction_23 <- kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP*C-RiiP_C_cAMP*kb_RiiP_cAMPxC__RiiP_C_cAMP
    reaction_78 <- kf_cAMPxRii__Rii_cAMP*cAMP*Rii-kb_cAMPxRii__Rii_cAMP*Rii_cAMP
    reaction_56 <- kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C*cAMP-Rii_C_cAMP*kb_Rii_CxcAMP__Rii_C_cAMP
    reaction_76 <- kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP*C-Rii_C_cAMP*kb_Rii_cAMPxC__Rii_C_cAMP
    reaction_62 <- Rii_C_cAMP*kf_Rii_C_cAMP__RiiP_C_cAMP
    reaction_58 <- -Rii_C*kb_RiixC__Rii_C+kf_RiixC__Rii_C*C*Rii
    reaction_44_ <- RiiP*kf_RiiPxCaN__RiiP_CaN*CaN-RiiP_CaN*kb_RiiPxCaN__RiiP_CaN
    reaction_33_ <- -kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP_CaN+kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP*CaN
    reaction_4_8 <- kf_RiiP_CaN__RiixCaN*RiiP_CaN
    reaction_3_7 <- RiiP_cAMP_CaN*kf_RiiP_cAMP_CaN__CaNXRii_cAMP
    reaction_1 <- kf_C_AKAR4*C*AKAR4-kb_C_AKAR4*AKAR4_C
    reaction_2 <- AKAR4_C*kcat_AKARp
    r_ <- AKAR4p;
    return(r_)
}

#
# AKAP79_AKAR4pOUT
#
# This function implements the user-defined function "AKAR4pOUT"
#
AKAP79_AKAR4pOUT <- function(t, state, parameters) {
    Rii        <- state[1]
    cAMP       <- state[2]
    RiiP       <- state[3]
    Rii_C      <- state[4]
    RiiP_cAMP  <- state[5]
    RiiP_C     <- state[6]
    RiiP_C_cAMP <- state[7]
    C          <- state[8]
    Rii_cAMP   <- state[9]
    Rii_C_cAMP <- state[10]
    CaN        <- state[11]
    RiiP_CaN   <- state[12]
    RiiP_cAMP_CaN <- state[13]
    AKAR4      <- state[14]
    AKAR4_C    <- state[15]
    AKAR4p     <- state[16]
    kf_Rii_C__RiiP_C <- parameters[1]
    kf_RiiP_CxcAMP__RiiP_C_cAMP <- parameters[2]
    kf_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[3]
    kb_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[4]
    kb_RiiPXcAMP__RiiP_cAMP <- parameters[5]
    kf_RiiPXcAMP__RiiP_cAMP <- parameters[6]
    kf_RiiPxC__RiiP_C <- parameters[7]
    kb_RiiPxC__RiiP_C <- parameters[8]
    kf_cAMPxRii__Rii_cAMP <- parameters[9]
    kb_cAMPxRii__Rii_cAMP <- parameters[10]
    kf_Rii_CxcAMP__Rii_C_cAMP <- parameters[11]
    kb_Rii_CxcAMP__Rii_C_cAMP <- parameters[12]
    kf_RiixC__Rii_C <- parameters[13]
    kf_Rii_cAMPxC__Rii_C_cAMP <- parameters[14]
    kb_Rii_cAMPxC__Rii_C_cAMP <- parameters[15]
    kf_Rii_C_cAMP__RiiP_C_cAMP <- parameters[16]
    kb_RiixC__Rii_C <- parameters[17]
    AKAPoff_1  <- parameters[18]
    AKAPoff_3  <- parameters[19]
    AKAPon_1   <- parameters[20]
    AKAPon_3   <- parameters[21]
    kf_C_AKAR4 <- parameters[22]
    kb_C_AKAR4 <- parameters[23]
    kcat_AKARp <- parameters[24]
    kmOFF      <- parameters[25]
    kmON       <- parameters[26]
    KD_T       <- parameters[27]
    b_AKAP     <- parameters[28]
    kf_RiiP_cAMP_CaN__CaNXRii_cAMP <- AKAPon_1*b_AKAP-(-1+b_AKAP)*AKAPoff_1
    kb_RiiPxCaN__RiiP_CaN <- -(-1+b_AKAP)*AKAPoff_3+b_AKAP*AKAPon_3
    kf_RiiP_CaN__RiixCaN <- AKAPon_1*b_AKAP-(-1+b_AKAP)*AKAPoff_1
    kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -(-1+b_AKAP)*AKAPoff_3+b_AKAP*AKAPon_3
    kf_RiiPxCaN__RiiP_CaN <- -(-1+b_AKAP)*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*kmOFF^(-1)+kmON^(-1)*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*b_AKAP
    kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -(-1+b_AKAP)*(kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN+kf_RiiP_CaN__RiixCaN)*kmOFF^(-1)+kmON^(-1)*(kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN+kf_RiiP_CaN__RiixCaN)*b_AKAP
    kb_RiiP_CxcAMP__RiiP_C_cAMP <- kf_RiiP_CxcAMP__RiiP_C_cAMP*KD_T
    reaction_51 <- Rii_C*kf_Rii_C__RiiP_C
    reaction_14 <- -RiiP_C*kb_RiiPxC__RiiP_C+kf_RiiPxC__RiiP_C*RiiP*C
    reaction_12 <- -kb_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C_cAMP+RiiP_C*cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP
    reaction_43 <- RiiP*kf_RiiPXcAMP__RiiP_cAMP*cAMP-RiiP_cAMP*kb_RiiPXcAMP__RiiP_cAMP
    reaction_23 <- kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP*C-RiiP_C_cAMP*kb_RiiP_cAMPxC__RiiP_C_cAMP
    reaction_78 <- kf_cAMPxRii__Rii_cAMP*cAMP*Rii-kb_cAMPxRii__Rii_cAMP*Rii_cAMP
    reaction_56 <- kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C*cAMP-Rii_C_cAMP*kb_Rii_CxcAMP__Rii_C_cAMP
    reaction_76 <- kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP*C-Rii_C_cAMP*kb_Rii_cAMPxC__Rii_C_cAMP
    reaction_62 <- Rii_C_cAMP*kf_Rii_C_cAMP__RiiP_C_cAMP
    reaction_58 <- -Rii_C*kb_RiixC__Rii_C+kf_RiixC__Rii_C*C*Rii
    reaction_44_ <- RiiP*kf_RiiPxCaN__RiiP_CaN*CaN-RiiP_CaN*kb_RiiPxCaN__RiiP_CaN
    reaction_33_ <- -kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP_CaN+kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP*CaN
    reaction_4_8 <- kf_RiiP_CaN__RiixCaN*RiiP_CaN
    reaction_3_7 <- RiiP_cAMP_CaN*kf_RiiP_cAMP_CaN__CaNXRii_cAMP
    reaction_1 <- kf_C_AKAR4*C*AKAR4-kb_C_AKAR4*AKAR4_C
    reaction_2 <- AKAR4_C*kcat_AKARp
    r_ <- AKAR4p;
    return(r_)
}
