#
# AKAP79.R
#
# R vector field functions for: AKAP79
#
# This file was generated by the program VFGEN, version: 2.6.0.dev3
# Generated on 15-Aug-2022 at 16:44
#


#
# AKAP79(t, state, parameters)
#
# The vector field function
#
AKAP79 <- function(t, state, parameters) {
    Rii        <- state[1]
    cAMP       <- state[2]
    RiiP       <- state[3]
    Rii_C      <- state[4]
    RiiP_cAMP  <- state[5]
    RiiP_C     <- state[6]
    RiiP_C_cAMP <- state[7]
    C          <- state[8]
    Rii_cAMP   <- state[9]
    Rii_C_cAMP <- state[10]
    CaN        <- state[11]
    RiiP_CaN   <- state[12]
    RiiP_cAMP_CaN <- state[13]
    AKAR4      <- state[14]
    AKAR4_C    <- state[15]
    AKAR4p     <- state[16]
    kf_Rii_C__RiiP_C <- parameters[1]
    kf_RiiP_CxcAMP__RiiP_C_cAMP <- parameters[2]
    kf_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[3]
    kb_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[4]
    kb_RiiPXcAMP__RiiP_cAMP <- parameters[5]
    kf_RiiPXcAMP__RiiP_cAMP <- parameters[6]
    kf_RiiPxC__RiiP_C <- parameters[7]
    kb_RiiPxC__RiiP_C <- parameters[8]
    kf_cAMPxRii__Rii_cAMP <- parameters[9]
    kb_cAMPxRii__Rii_cAMP <- parameters[10]
    kf_Rii_CxcAMP__Rii_C_cAMP <- parameters[11]
    kb_Rii_CxcAMP__Rii_C_cAMP <- parameters[12]
    kf_RiixC__Rii_C <- parameters[13]
    kf_Rii_cAMPxC__Rii_C_cAMP <- parameters[14]
    kb_Rii_cAMPxC__Rii_C_cAMP <- parameters[15]
    kf_Rii_C_cAMP__RiiP_C_cAMP <- parameters[16]
    kb_RiixC__Rii_C <- parameters[17]
    AKAPoff_1  <- parameters[18]
    AKAPoff_3  <- parameters[19]
    AKAPon_1   <- parameters[20]
    AKAPon_3   <- parameters[21]
    kf_C_AKAR4 <- parameters[22]
    kb_C_AKAR4 <- parameters[23]
    kcat_AKARp <- parameters[24]
    kmOFF      <- parameters[25]
    kmON       <- parameters[26]
    KD_T       <- parameters[27]
    b_AKAP     <- parameters[28]

    kf_RiiP_cAMP_CaN__CaNXRii_cAMP <- b_AKAP*AKAPon_1-AKAPoff_1*(-1+b_AKAP);
    kb_RiiPxCaN__RiiP_CaN <- -AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3;
    kf_RiiP_CaN__RiixCaN <- b_AKAP*AKAPon_1-AKAPoff_1*(-1+b_AKAP);
    kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3;
    kf_RiiPxCaN__RiiP_CaN <- -kmOFF^(-1)*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*(-1+b_AKAP)+b_AKAP*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*kmON^(-1);
    kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -kmOFF^(-1)*(kf_RiiP_CaN__RiixCaN+kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN)*(-1+b_AKAP)+b_AKAP*(kf_RiiP_CaN__RiixCaN+kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN)*kmON^(-1);
    kb_RiiP_CxcAMP__RiiP_C_cAMP <- KD_T*kf_RiiP_CxcAMP__RiiP_C_cAMP;
    reaction_51 <- Rii_C*kf_Rii_C__RiiP_C;
    reaction_14 <- RiiP*kf_RiiPxC__RiiP_C*C-RiiP_C*kb_RiiPxC__RiiP_C;
    reaction_12 <- -RiiP_C_cAMP*kb_RiiP_CxcAMP__RiiP_C_cAMP+RiiP_C*cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP;
    reaction_43 <- -RiiP_cAMP*kb_RiiPXcAMP__RiiP_cAMP+kf_RiiPXcAMP__RiiP_cAMP*RiiP*cAMP;
    reaction_23 <- -RiiP_C_cAMP*kb_RiiP_cAMPxC__RiiP_C_cAMP+kf_RiiP_cAMPxC__RiiP_C_cAMP*C*RiiP_cAMP;
    reaction_78 <- -Rii_cAMP*kb_cAMPxRii__Rii_cAMP+kf_cAMPxRii__Rii_cAMP*Rii*cAMP;
    reaction_56 <- -kb_Rii_CxcAMP__Rii_C_cAMP*Rii_C_cAMP+Rii_C*kf_Rii_CxcAMP__Rii_C_cAMP*cAMP;
    reaction_76 <- -kb_Rii_cAMPxC__Rii_C_cAMP*Rii_C_cAMP+Rii_cAMP*C*kf_Rii_cAMPxC__Rii_C_cAMP;
    reaction_62 <- Rii_C_cAMP*kf_Rii_C_cAMP__RiiP_C_cAMP;
    reaction_58 <- -Rii_C*kb_RiixC__Rii_C+kf_RiixC__Rii_C*Rii*C;
    reaction_44_ <- RiiP*CaN*kf_RiiPxCaN__RiiP_CaN-kb_RiiPxCaN__RiiP_CaN*RiiP_CaN;
    reaction_33_ <- kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*CaN*RiiP_cAMP-RiiP_cAMP_CaN*kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN;
    reaction_4_8 <- RiiP_CaN*kf_RiiP_CaN__RiixCaN;
    reaction_3_7 <- RiiP_cAMP_CaN*kf_RiiP_cAMP_CaN__CaNXRii_cAMP;
    reaction_1 <- -kb_C_AKAR4*AKAR4_C+kf_C_AKAR4*AKAR4*C;
    reaction_2 <- kcat_AKARp*AKAR4_C;
    vf_ <- vector(len = 16)
    vf_[1] = -reaction_78+reaction_4_8-reaction_58;
    vf_[2] = -reaction_78-reaction_12-reaction_56-reaction_43;
    vf_[3] = -reaction_14-reaction_44_-reaction_43;
    vf_[4] = -reaction_56-reaction_51+reaction_58;
    vf_[5] = -reaction_23-reaction_33_+reaction_43;
    vf_[6] = reaction_14-reaction_12+reaction_51;
    vf_[7] = reaction_23+reaction_62+reaction_12;
    vf_[8] = -reaction_76-reaction_23-reaction_14-reaction_1+reaction_2-reaction_58;
    vf_[9] = -reaction_76+reaction_3_7+reaction_78;
    vf_[10] = reaction_76-reaction_62+reaction_56;
    vf_[11] = reaction_3_7-reaction_44_-reaction_33_+reaction_4_8;
    vf_[12] = reaction_44_-reaction_4_8;
    vf_[13] = -reaction_3_7+reaction_33_;
    vf_[14] = -reaction_1;
    vf_[15] = reaction_1-reaction_2;
    vf_[16] = reaction_2;
    return(list(vf_))
}

#
# AKAP79_jac(t, state, parameters)
#
# The jacobian function
#
AKAP79_jac <- function(t, state, parameters) {
    Rii        <- state[1]
    cAMP       <- state[2]
    RiiP       <- state[3]
    Rii_C      <- state[4]
    RiiP_cAMP  <- state[5]
    RiiP_C     <- state[6]
    RiiP_C_cAMP <- state[7]
    C          <- state[8]
    Rii_cAMP   <- state[9]
    Rii_C_cAMP <- state[10]
    CaN        <- state[11]
    RiiP_CaN   <- state[12]
    RiiP_cAMP_CaN <- state[13]
    AKAR4      <- state[14]
    AKAR4_C    <- state[15]
    AKAR4p     <- state[16]
    kf_Rii_C__RiiP_C <- parameters[1]
    kf_RiiP_CxcAMP__RiiP_C_cAMP <- parameters[2]
    kf_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[3]
    kb_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[4]
    kb_RiiPXcAMP__RiiP_cAMP <- parameters[5]
    kf_RiiPXcAMP__RiiP_cAMP <- parameters[6]
    kf_RiiPxC__RiiP_C <- parameters[7]
    kb_RiiPxC__RiiP_C <- parameters[8]
    kf_cAMPxRii__Rii_cAMP <- parameters[9]
    kb_cAMPxRii__Rii_cAMP <- parameters[10]
    kf_Rii_CxcAMP__Rii_C_cAMP <- parameters[11]
    kb_Rii_CxcAMP__Rii_C_cAMP <- parameters[12]
    kf_RiixC__Rii_C <- parameters[13]
    kf_Rii_cAMPxC__Rii_C_cAMP <- parameters[14]
    kb_Rii_cAMPxC__Rii_C_cAMP <- parameters[15]
    kf_Rii_C_cAMP__RiiP_C_cAMP <- parameters[16]
    kb_RiixC__Rii_C <- parameters[17]
    AKAPoff_1  <- parameters[18]
    AKAPoff_3  <- parameters[19]
    AKAPon_1   <- parameters[20]
    AKAPon_3   <- parameters[21]
    kf_C_AKAR4 <- parameters[22]
    kb_C_AKAR4 <- parameters[23]
    kcat_AKARp <- parameters[24]
    kmOFF      <- parameters[25]
    kmON       <- parameters[26]
    KD_T       <- parameters[27]
    b_AKAP     <- parameters[28]
    jac_ = matrix(nrow = 16, ncol = 16)
    jac_[1,1] = -kf_cAMPxRii__Rii_cAMP*cAMP-kf_RiixC__Rii_C*C
    jac_[1,2] = -kf_cAMPxRii__Rii_cAMP*Rii
    jac_[1,3] = 0
    jac_[1,4] = kb_RiixC__Rii_C
    jac_[1,5] = 0
    jac_[1,6] = 0
    jac_[1,7] = 0
    jac_[1,8] = -kf_RiixC__Rii_C*Rii
    jac_[1,9] = kb_cAMPxRii__Rii_cAMP
    jac_[1,10] = 0
    jac_[1,11] = 0
    jac_[1,12] = b_AKAP*AKAPon_1-AKAPoff_1*(-1+b_AKAP)
    jac_[1,13] = 0
    jac_[1,14] = 0
    jac_[1,15] = 0
    jac_[1,16] = 0
    jac_[2,1] = -kf_cAMPxRii__Rii_cAMP*cAMP
    jac_[2,2] = -Rii_C*kf_Rii_CxcAMP__Rii_C_cAMP-kf_cAMPxRii__Rii_cAMP*Rii-kf_RiiPXcAMP__RiiP_cAMP*RiiP-RiiP_C*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[2,3] = -kf_RiiPXcAMP__RiiP_cAMP*cAMP
    jac_[2,4] = -kf_Rii_CxcAMP__Rii_C_cAMP*cAMP
    jac_[2,5] = kb_RiiPXcAMP__RiiP_cAMP
    jac_[2,6] = -cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[2,7] = KD_T*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[2,8] = 0
    jac_[2,9] = kb_cAMPxRii__Rii_cAMP
    jac_[2,10] = kb_Rii_CxcAMP__Rii_C_cAMP
    jac_[2,11] = 0
    jac_[2,12] = 0
    jac_[2,13] = 0
    jac_[2,14] = 0
    jac_[2,15] = 0
    jac_[2,16] = 0
    jac_[3,1] = 0
    jac_[3,2] = -kf_RiiPXcAMP__RiiP_cAMP*RiiP
    jac_[3,3] = -kf_RiiPxC__RiiP_C*C+(kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*CaN-kf_RiiPXcAMP__RiiP_cAMP*cAMP
    jac_[3,4] = 0
    jac_[3,5] = kb_RiiPXcAMP__RiiP_cAMP
    jac_[3,6] = kb_RiiPxC__RiiP_C
    jac_[3,7] = 0
    jac_[3,8] = -RiiP*kf_RiiPxC__RiiP_C
    jac_[3,9] = 0
    jac_[3,10] = 0
    jac_[3,11] = (kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*RiiP
    jac_[3,12] = -AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3
    jac_[3,13] = 0
    jac_[3,14] = 0
    jac_[3,15] = 0
    jac_[3,16] = 0
    jac_[4,1] = kf_RiixC__Rii_C*C
    jac_[4,2] = -Rii_C*kf_Rii_CxcAMP__Rii_C_cAMP
    jac_[4,3] = 0
    jac_[4,4] = -kf_Rii_CxcAMP__Rii_C_cAMP*cAMP-kf_Rii_C__RiiP_C-kb_RiixC__Rii_C
    jac_[4,5] = 0
    jac_[4,6] = 0
    jac_[4,7] = 0
    jac_[4,8] = kf_RiixC__Rii_C*Rii
    jac_[4,9] = 0
    jac_[4,10] = kb_Rii_CxcAMP__Rii_C_cAMP
    jac_[4,11] = 0
    jac_[4,12] = 0
    jac_[4,13] = 0
    jac_[4,14] = 0
    jac_[4,15] = 0
    jac_[4,16] = 0
    jac_[5,1] = 0
    jac_[5,2] = kf_RiiPXcAMP__RiiP_cAMP*RiiP
    jac_[5,3] = kf_RiiPXcAMP__RiiP_cAMP*cAMP
    jac_[5,4] = 0
    jac_[5,5] = -kf_RiiP_cAMPxC__RiiP_C_cAMP*C+(kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*CaN-kb_RiiPXcAMP__RiiP_cAMP
    jac_[5,6] = 0
    jac_[5,7] = kb_RiiP_cAMPxC__RiiP_C_cAMP
    jac_[5,8] = -kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP
    jac_[5,9] = 0
    jac_[5,10] = 0
    jac_[5,11] = (kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*RiiP_cAMP
    jac_[5,12] = 0
    jac_[5,13] = -AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3
    jac_[5,14] = 0
    jac_[5,15] = 0
    jac_[5,16] = 0
    jac_[6,1] = 0
    jac_[6,2] = -RiiP_C*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[6,3] = kf_RiiPxC__RiiP_C*C
    jac_[6,4] = kf_Rii_C__RiiP_C
    jac_[6,5] = 0
    jac_[6,6] = -cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP-kb_RiiPxC__RiiP_C
    jac_[6,7] = KD_T*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[6,8] = RiiP*kf_RiiPxC__RiiP_C
    jac_[6,9] = 0
    jac_[6,10] = 0
    jac_[6,11] = 0
    jac_[6,12] = 0
    jac_[6,13] = 0
    jac_[6,14] = 0
    jac_[6,15] = 0
    jac_[6,16] = 0
    jac_[7,1] = 0
    jac_[7,2] = RiiP_C*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[7,3] = 0
    jac_[7,4] = 0
    jac_[7,5] = kf_RiiP_cAMPxC__RiiP_C_cAMP*C
    jac_[7,6] = cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP
    jac_[7,7] = -KD_T*kf_RiiP_CxcAMP__RiiP_C_cAMP-kb_RiiP_cAMPxC__RiiP_C_cAMP
    jac_[7,8] = kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP
    jac_[7,9] = 0
    jac_[7,10] = kf_Rii_C_cAMP__RiiP_C_cAMP
    jac_[7,11] = 0
    jac_[7,12] = 0
    jac_[7,13] = 0
    jac_[7,14] = 0
    jac_[7,15] = 0
    jac_[7,16] = 0
    jac_[8,1] = -kf_RiixC__Rii_C*C
    jac_[8,2] = 0
    jac_[8,3] = -kf_RiiPxC__RiiP_C*C
    jac_[8,4] = kb_RiixC__Rii_C
    jac_[8,5] = -kf_RiiP_cAMPxC__RiiP_C_cAMP*C
    jac_[8,6] = kb_RiiPxC__RiiP_C
    jac_[8,7] = kb_RiiP_cAMPxC__RiiP_C_cAMP
    jac_[8,8] = -Rii_cAMP*kf_Rii_cAMPxC__Rii_C_cAMP-kf_RiixC__Rii_C*Rii-kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP-kf_C_AKAR4*AKAR4-RiiP*kf_RiiPxC__RiiP_C
    jac_[8,9] = -C*kf_Rii_cAMPxC__Rii_C_cAMP
    jac_[8,10] = kb_Rii_cAMPxC__Rii_C_cAMP
    jac_[8,11] = 0
    jac_[8,12] = 0
    jac_[8,13] = 0
    jac_[8,14] = -kf_C_AKAR4*C
    jac_[8,15] = kb_C_AKAR4+kcat_AKARp
    jac_[8,16] = 0
    jac_[9,1] = kf_cAMPxRii__Rii_cAMP*cAMP
    jac_[9,2] = kf_cAMPxRii__Rii_cAMP*Rii
    jac_[9,3] = 0
    jac_[9,4] = 0
    jac_[9,5] = 0
    jac_[9,6] = 0
    jac_[9,7] = 0
    jac_[9,8] = -Rii_cAMP*kf_Rii_cAMPxC__Rii_C_cAMP
    jac_[9,9] = -C*kf_Rii_cAMPxC__Rii_C_cAMP-kb_cAMPxRii__Rii_cAMP
    jac_[9,10] = kb_Rii_cAMPxC__Rii_C_cAMP
    jac_[9,11] = 0
    jac_[9,12] = 0
    jac_[9,13] = b_AKAP*AKAPon_1-AKAPoff_1*(-1+b_AKAP)
    jac_[9,14] = 0
    jac_[9,15] = 0
    jac_[9,16] = 0
    jac_[10,1] = 0
    jac_[10,2] = Rii_C*kf_Rii_CxcAMP__Rii_C_cAMP
    jac_[10,3] = 0
    jac_[10,4] = kf_Rii_CxcAMP__Rii_C_cAMP*cAMP
    jac_[10,5] = 0
    jac_[10,6] = 0
    jac_[10,7] = 0
    jac_[10,8] = Rii_cAMP*kf_Rii_cAMPxC__Rii_C_cAMP
    jac_[10,9] = C*kf_Rii_cAMPxC__Rii_C_cAMP
    jac_[10,10] = -kb_Rii_CxcAMP__Rii_C_cAMP-kb_Rii_cAMPxC__Rii_C_cAMP-kf_Rii_C_cAMP__RiiP_C_cAMP
    jac_[10,11] = 0
    jac_[10,12] = 0
    jac_[10,13] = 0
    jac_[10,14] = 0
    jac_[10,15] = 0
    jac_[10,16] = 0
    jac_[11,1] = 0
    jac_[11,2] = 0
    jac_[11,3] = (kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*CaN
    jac_[11,4] = 0
    jac_[11,5] = (kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*CaN
    jac_[11,6] = 0
    jac_[11,7] = 0
    jac_[11,8] = 0
    jac_[11,9] = 0
    jac_[11,10] = 0
    jac_[11,11] = (kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*RiiP_cAMP+(kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*RiiP
    jac_[11,12] = b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)
    jac_[11,13] = b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)
    jac_[11,14] = 0
    jac_[11,15] = 0
    jac_[11,16] = 0
    jac_[12,1] = 0
    jac_[12,2] = 0
    jac_[12,3] = -(kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*CaN
    jac_[12,4] = 0
    jac_[12,5] = 0
    jac_[12,6] = 0
    jac_[12,7] = 0
    jac_[12,8] = 0
    jac_[12,9] = 0
    jac_[12,10] = 0
    jac_[12,11] = -(kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*RiiP
    jac_[12,12] = -b_AKAP*AKAPon_1+AKAPoff_3*(-1+b_AKAP)-b_AKAP*AKAPon_3+AKAPoff_1*(-1+b_AKAP)
    jac_[12,13] = 0
    jac_[12,14] = 0
    jac_[12,15] = 0
    jac_[12,16] = 0
    jac_[13,1] = 0
    jac_[13,2] = 0
    jac_[13,3] = 0
    jac_[13,4] = 0
    jac_[13,5] = -(kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*CaN
    jac_[13,6] = 0
    jac_[13,7] = 0
    jac_[13,8] = 0
    jac_[13,9] = 0
    jac_[13,10] = 0
    jac_[13,11] = -(kmOFF^(-1)*(-1+b_AKAP)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP))-b_AKAP*kmON^(-1)*(b_AKAP*AKAPon_1-AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3-AKAPoff_1*(-1+b_AKAP)))*RiiP_cAMP
    jac_[13,12] = 0
    jac_[13,13] = -b_AKAP*AKAPon_1+AKAPoff_3*(-1+b_AKAP)-b_AKAP*AKAPon_3+AKAPoff_1*(-1+b_AKAP)
    jac_[13,14] = 0
    jac_[13,15] = 0
    jac_[13,16] = 0
    jac_[14,1] = 0
    jac_[14,2] = 0
    jac_[14,3] = 0
    jac_[14,4] = 0
    jac_[14,5] = 0
    jac_[14,6] = 0
    jac_[14,7] = 0
    jac_[14,8] = -kf_C_AKAR4*AKAR4
    jac_[14,9] = 0
    jac_[14,10] = 0
    jac_[14,11] = 0
    jac_[14,12] = 0
    jac_[14,13] = 0
    jac_[14,14] = -kf_C_AKAR4*C
    jac_[14,15] = kb_C_AKAR4
    jac_[14,16] = 0
    jac_[15,1] = 0
    jac_[15,2] = 0
    jac_[15,3] = 0
    jac_[15,4] = 0
    jac_[15,5] = 0
    jac_[15,6] = 0
    jac_[15,7] = 0
    jac_[15,8] = kf_C_AKAR4*AKAR4
    jac_[15,9] = 0
    jac_[15,10] = 0
    jac_[15,11] = 0
    jac_[15,12] = 0
    jac_[15,13] = 0
    jac_[15,14] = kf_C_AKAR4*C
    jac_[15,15] = -kb_C_AKAR4-kcat_AKARp
    jac_[15,16] = 0
    jac_[16,1] = 0
    jac_[16,2] = 0
    jac_[16,3] = 0
    jac_[16,4] = 0
    jac_[16,5] = 0
    jac_[16,6] = 0
    jac_[16,7] = 0
    jac_[16,8] = 0
    jac_[16,9] = 0
    jac_[16,10] = 0
    jac_[16,11] = 0
    jac_[16,12] = 0
    jac_[16,13] = 0
    jac_[16,14] = 0
    jac_[16,15] = kcat_AKARp
    jac_[16,16] = 0
    return(jac_)
}


#
# AKAP79_sol_AKAR4pOUT
#
# This function implements the user-defined function "AKAR4pOUT"
#
AKAP79_sol_AKAR4pOUT <- function(sol, parameters) {
    t <- sol[, 1]
    Rii        <- sol[, 2]
    cAMP       <- sol[, 3]
    RiiP       <- sol[, 4]
    Rii_C      <- sol[, 5]
    RiiP_cAMP  <- sol[, 6]
    RiiP_C     <- sol[, 7]
    RiiP_C_cAMP <- sol[, 8]
    C          <- sol[, 9]
    Rii_cAMP   <- sol[, 10]
    Rii_C_cAMP <- sol[, 11]
    CaN        <- sol[, 12]
    RiiP_CaN   <- sol[, 13]
    RiiP_cAMP_CaN <- sol[, 14]
    AKAR4      <- sol[, 15]
    AKAR4_C    <- sol[, 16]
    AKAR4p     <- sol[, 17]
    kf_Rii_C__RiiP_C <- parameters[1]
    kf_RiiP_CxcAMP__RiiP_C_cAMP <- parameters[2]
    kf_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[3]
    kb_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[4]
    kb_RiiPXcAMP__RiiP_cAMP <- parameters[5]
    kf_RiiPXcAMP__RiiP_cAMP <- parameters[6]
    kf_RiiPxC__RiiP_C <- parameters[7]
    kb_RiiPxC__RiiP_C <- parameters[8]
    kf_cAMPxRii__Rii_cAMP <- parameters[9]
    kb_cAMPxRii__Rii_cAMP <- parameters[10]
    kf_Rii_CxcAMP__Rii_C_cAMP <- parameters[11]
    kb_Rii_CxcAMP__Rii_C_cAMP <- parameters[12]
    kf_RiixC__Rii_C <- parameters[13]
    kf_Rii_cAMPxC__Rii_C_cAMP <- parameters[14]
    kb_Rii_cAMPxC__Rii_C_cAMP <- parameters[15]
    kf_Rii_C_cAMP__RiiP_C_cAMP <- parameters[16]
    kb_RiixC__Rii_C <- parameters[17]
    AKAPoff_1  <- parameters[18]
    AKAPoff_3  <- parameters[19]
    AKAPon_1   <- parameters[20]
    AKAPon_3   <- parameters[21]
    kf_C_AKAR4 <- parameters[22]
    kb_C_AKAR4 <- parameters[23]
    kcat_AKARp <- parameters[24]
    kmOFF      <- parameters[25]
    kmON       <- parameters[26]
    KD_T       <- parameters[27]
    b_AKAP     <- parameters[28]
    kf_RiiP_cAMP_CaN__CaNXRii_cAMP <- b_AKAP*AKAPon_1-AKAPoff_1*(-1+b_AKAP)
    kb_RiiPxCaN__RiiP_CaN <- -AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3
    kf_RiiP_CaN__RiixCaN <- b_AKAP*AKAPon_1-AKAPoff_1*(-1+b_AKAP)
    kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3
    kf_RiiPxCaN__RiiP_CaN <- -kmOFF^(-1)*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*(-1+b_AKAP)+b_AKAP*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*kmON^(-1)
    kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -kmOFF^(-1)*(kf_RiiP_CaN__RiixCaN+kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN)*(-1+b_AKAP)+b_AKAP*(kf_RiiP_CaN__RiixCaN+kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN)*kmON^(-1)
    kb_RiiP_CxcAMP__RiiP_C_cAMP <- KD_T*kf_RiiP_CxcAMP__RiiP_C_cAMP
    reaction_51 <- Rii_C*kf_Rii_C__RiiP_C
    reaction_14 <- RiiP*kf_RiiPxC__RiiP_C*C-RiiP_C*kb_RiiPxC__RiiP_C
    reaction_12 <- -RiiP_C_cAMP*kb_RiiP_CxcAMP__RiiP_C_cAMP+RiiP_C*cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP
    reaction_43 <- -RiiP_cAMP*kb_RiiPXcAMP__RiiP_cAMP+kf_RiiPXcAMP__RiiP_cAMP*RiiP*cAMP
    reaction_23 <- -RiiP_C_cAMP*kb_RiiP_cAMPxC__RiiP_C_cAMP+kf_RiiP_cAMPxC__RiiP_C_cAMP*C*RiiP_cAMP
    reaction_78 <- -Rii_cAMP*kb_cAMPxRii__Rii_cAMP+kf_cAMPxRii__Rii_cAMP*Rii*cAMP
    reaction_56 <- -kb_Rii_CxcAMP__Rii_C_cAMP*Rii_C_cAMP+Rii_C*kf_Rii_CxcAMP__Rii_C_cAMP*cAMP
    reaction_76 <- -kb_Rii_cAMPxC__Rii_C_cAMP*Rii_C_cAMP+Rii_cAMP*C*kf_Rii_cAMPxC__Rii_C_cAMP
    reaction_62 <- Rii_C_cAMP*kf_Rii_C_cAMP__RiiP_C_cAMP
    reaction_58 <- -Rii_C*kb_RiixC__Rii_C+kf_RiixC__Rii_C*Rii*C
    reaction_44_ <- RiiP*CaN*kf_RiiPxCaN__RiiP_CaN-kb_RiiPxCaN__RiiP_CaN*RiiP_CaN
    reaction_33_ <- kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*CaN*RiiP_cAMP-RiiP_cAMP_CaN*kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN
    reaction_4_8 <- RiiP_CaN*kf_RiiP_CaN__RiixCaN
    reaction_3_7 <- RiiP_cAMP_CaN*kf_RiiP_cAMP_CaN__CaNXRii_cAMP
    reaction_1 <- -kb_C_AKAR4*AKAR4_C+kf_C_AKAR4*AKAR4*C
    reaction_2 <- kcat_AKARp*AKAR4_C
    r_ <- AKAR4p;
    return(r_)
}

#
# AKAP79_AKAR4pOUT
#
# This function implements the user-defined function "AKAR4pOUT"
#
AKAP79_AKAR4pOUT <- function(t, state, parameters) {
    Rii        <- state[1]
    cAMP       <- state[2]
    RiiP       <- state[3]
    Rii_C      <- state[4]
    RiiP_cAMP  <- state[5]
    RiiP_C     <- state[6]
    RiiP_C_cAMP <- state[7]
    C          <- state[8]
    Rii_cAMP   <- state[9]
    Rii_C_cAMP <- state[10]
    CaN        <- state[11]
    RiiP_CaN   <- state[12]
    RiiP_cAMP_CaN <- state[13]
    AKAR4      <- state[14]
    AKAR4_C    <- state[15]
    AKAR4p     <- state[16]
    kf_Rii_C__RiiP_C <- parameters[1]
    kf_RiiP_CxcAMP__RiiP_C_cAMP <- parameters[2]
    kf_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[3]
    kb_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[4]
    kb_RiiPXcAMP__RiiP_cAMP <- parameters[5]
    kf_RiiPXcAMP__RiiP_cAMP <- parameters[6]
    kf_RiiPxC__RiiP_C <- parameters[7]
    kb_RiiPxC__RiiP_C <- parameters[8]
    kf_cAMPxRii__Rii_cAMP <- parameters[9]
    kb_cAMPxRii__Rii_cAMP <- parameters[10]
    kf_Rii_CxcAMP__Rii_C_cAMP <- parameters[11]
    kb_Rii_CxcAMP__Rii_C_cAMP <- parameters[12]
    kf_RiixC__Rii_C <- parameters[13]
    kf_Rii_cAMPxC__Rii_C_cAMP <- parameters[14]
    kb_Rii_cAMPxC__Rii_C_cAMP <- parameters[15]
    kf_Rii_C_cAMP__RiiP_C_cAMP <- parameters[16]
    kb_RiixC__Rii_C <- parameters[17]
    AKAPoff_1  <- parameters[18]
    AKAPoff_3  <- parameters[19]
    AKAPon_1   <- parameters[20]
    AKAPon_3   <- parameters[21]
    kf_C_AKAR4 <- parameters[22]
    kb_C_AKAR4 <- parameters[23]
    kcat_AKARp <- parameters[24]
    kmOFF      <- parameters[25]
    kmON       <- parameters[26]
    KD_T       <- parameters[27]
    b_AKAP     <- parameters[28]
    kf_RiiP_cAMP_CaN__CaNXRii_cAMP <- b_AKAP*AKAPon_1-AKAPoff_1*(-1+b_AKAP)
    kb_RiiPxCaN__RiiP_CaN <- -AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3
    kf_RiiP_CaN__RiixCaN <- b_AKAP*AKAPon_1-AKAPoff_1*(-1+b_AKAP)
    kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3
    kf_RiiPxCaN__RiiP_CaN <- -kmOFF^(-1)*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*(-1+b_AKAP)+b_AKAP*(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*kmON^(-1)
    kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -kmOFF^(-1)*(kf_RiiP_CaN__RiixCaN+kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN)*(-1+b_AKAP)+b_AKAP*(kf_RiiP_CaN__RiixCaN+kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN)*kmON^(-1)
    kb_RiiP_CxcAMP__RiiP_C_cAMP <- KD_T*kf_RiiP_CxcAMP__RiiP_C_cAMP
    reaction_51 <- Rii_C*kf_Rii_C__RiiP_C
    reaction_14 <- RiiP*kf_RiiPxC__RiiP_C*C-RiiP_C*kb_RiiPxC__RiiP_C
    reaction_12 <- -RiiP_C_cAMP*kb_RiiP_CxcAMP__RiiP_C_cAMP+RiiP_C*cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP
    reaction_43 <- -RiiP_cAMP*kb_RiiPXcAMP__RiiP_cAMP+kf_RiiPXcAMP__RiiP_cAMP*RiiP*cAMP
    reaction_23 <- -RiiP_C_cAMP*kb_RiiP_cAMPxC__RiiP_C_cAMP+kf_RiiP_cAMPxC__RiiP_C_cAMP*C*RiiP_cAMP
    reaction_78 <- -Rii_cAMP*kb_cAMPxRii__Rii_cAMP+kf_cAMPxRii__Rii_cAMP*Rii*cAMP
    reaction_56 <- -kb_Rii_CxcAMP__Rii_C_cAMP*Rii_C_cAMP+Rii_C*kf_Rii_CxcAMP__Rii_C_cAMP*cAMP
    reaction_76 <- -kb_Rii_cAMPxC__Rii_C_cAMP*Rii_C_cAMP+Rii_cAMP*C*kf_Rii_cAMPxC__Rii_C_cAMP
    reaction_62 <- Rii_C_cAMP*kf_Rii_C_cAMP__RiiP_C_cAMP
    reaction_58 <- -Rii_C*kb_RiixC__Rii_C+kf_RiixC__Rii_C*Rii*C
    reaction_44_ <- RiiP*CaN*kf_RiiPxCaN__RiiP_CaN-kb_RiiPxCaN__RiiP_CaN*RiiP_CaN
    reaction_33_ <- kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*CaN*RiiP_cAMP-RiiP_cAMP_CaN*kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN
    reaction_4_8 <- RiiP_CaN*kf_RiiP_CaN__RiixCaN
    reaction_3_7 <- RiiP_cAMP_CaN*kf_RiiP_cAMP_CaN__CaNXRii_cAMP
    reaction_1 <- -kb_C_AKAR4*AKAR4_C+kf_C_AKAR4*AKAR4*C
    reaction_2 <- kcat_AKARp*AKAR4_C
    r_ <- AKAR4p;
    return(r_)
}
