AKAP79_out <- function(t, state, parameters) {
    Rii        <- state[1]
    cAMP       <- state[2]
    RiiP       <- state[3]
    Rii_C      <- state[4]
    RiiP_cAMP  <- state[5]
    RiiP_C     <- state[6]
    RiiP_C_cAMP <- state[7]
    C          <- state[8]
    Rii_cAMP   <- state[9]
    Rii_C_cAMP <- state[10]
    CaN        <- state[11]
    RiiP_CaN   <- state[12]
    RiiP_cAMP_CaN <- state[13]
    AKAR4      <- state[14]
    AKAR4_C    <- state[15]
    AKAR4p     <- state[16]
    kf_Rii_C__RiiP_C <- parameters[1]
    kf_RiiP_CxcAMP__RiiP_C_cAMP <- parameters[2]
    kf_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[3]
    kb_RiiP_cAMPxC__RiiP_C_cAMP <- parameters[4]
    kb_RiiPXcAMP__RiiP_cAMP <- parameters[5]
    kf_RiiPXcAMP__RiiP_cAMP <- parameters[6]
    kf_RiiPxC__RiiP_C <- parameters[7]
    kb_RiiPxC__RiiP_C <- parameters[8]
    kf_cAMPxRii__Rii_cAMP <- parameters[9]
    kb_cAMPxRii__Rii_cAMP <- parameters[10]
    kf_Rii_CxcAMP__Rii_C_cAMP <- parameters[11]
    kb_Rii_CxcAMP__Rii_C_cAMP <- parameters[12]
    kf_RiixC__Rii_C <- parameters[13]
    kf_Rii_cAMPxC__Rii_C_cAMP <- parameters[14]
    kb_Rii_cAMPxC__Rii_C_cAMP <- parameters[15]
    kf_Rii_C_cAMP__RiiP_C_cAMP <- parameters[16]
    kb_RiixC__Rii_C <- parameters[17]
    AKAPoff_1  <- parameters[18]
    AKAPoff_3  <- parameters[19]
    AKAPon_1   <- parameters[20]
    AKAPon_3   <- parameters[21]
    kf_C_AKAR4 <- parameters[22]
    kb_C_AKAR4 <- parameters[23]
    kcat_AKARp <- parameters[24]
    kmOFF      <- parameters[25]
    kmON       <- parameters[26]
    KD_T       <- parameters[27]
    b_AKAP     <- parameters[28]

    kf_RiiP_cAMP_CaN__CaNXRii_cAMP <- -(-1+b_AKAP)*AKAPoff_1+b_AKAP*AKAPon_1;
    kb_RiiPxCaN__RiiP_CaN <- -AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3;
    kf_RiiP_CaN__RiixCaN <- -(-1+b_AKAP)*AKAPoff_1+b_AKAP*AKAPon_1;
    kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -AKAPoff_3*(-1+b_AKAP)+b_AKAP*AKAPon_3;
    kf_RiiPxCaN__RiiP_CaN <- -(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*kmOFF^(-1)*(-1+b_AKAP)+(kb_RiiPxCaN__RiiP_CaN+kf_RiiP_cAMP_CaN__CaNXRii_cAMP)*b_AKAP*kmON^(-1);
    kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN <- -(kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN+kf_RiiP_CaN__RiixCaN)*kmOFF^(-1)*(-1+b_AKAP)+(kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN+kf_RiiP_CaN__RiixCaN)*b_AKAP*kmON^(-1);
    kb_RiiP_CxcAMP__RiiP_C_cAMP <- kf_RiiP_CxcAMP__RiiP_C_cAMP*KD_T;
    reaction_51 <- Rii_C*kf_Rii_C__RiiP_C;
    reaction_14 <- RiiP*C*kf_RiiPxC__RiiP_C-RiiP_C*kb_RiiPxC__RiiP_C;
    reaction_12 <- RiiP_C*cAMP*kf_RiiP_CxcAMP__RiiP_C_cAMP-kb_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C_cAMP;
    reaction_43 <- RiiP*kf_RiiPXcAMP__RiiP_cAMP*cAMP-RiiP_cAMP*kb_RiiPXcAMP__RiiP_cAMP;
    reaction_23 <- kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP*C-RiiP_C_cAMP*kb_RiiP_cAMPxC__RiiP_C_cAMP;
    reaction_78 <- -kb_cAMPxRii__Rii_cAMP*Rii_cAMP+kf_cAMPxRii__Rii_cAMP*cAMP*Rii;
    reaction_56 <- -kb_Rii_CxcAMP__Rii_C_cAMP*Rii_C_cAMP+cAMP*kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C;
    reaction_76 <- -kb_Rii_cAMPxC__Rii_C_cAMP*Rii_C_cAMP+Rii_cAMP*C*kf_Rii_cAMPxC__Rii_C_cAMP;
    reaction_62 <- kf_Rii_C_cAMP__RiiP_C_cAMP*Rii_C_cAMP;
    reaction_58 <- -Rii_C*kb_RiixC__Rii_C+kf_RiixC__Rii_C*C*Rii;
    reaction_44_ <- RiiP*kf_RiiPxCaN__RiiP_CaN*CaN-RiiP_CaN*kb_RiiPxCaN__RiiP_CaN;
    reaction_33_ <- -kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP_CaN+kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP*CaN;
    reaction_4_8 <- RiiP_CaN*kf_RiiP_CaN__RiixCaN;
    reaction_3_7 <- kf_RiiP_cAMP_CaN__CaNXRii_cAMP*RiiP_cAMP_CaN;
    reaction_1 <- kf_C_AKAR4*C*AKAR4-AKAR4_C*kb_C_AKAR4;
    reaction_2 <- AKAR4_C*kcat_AKARp;
    r_ <-vector(len=       1)
    r_[1] <- AKAR4p;
    return(r_)
}
