#include <stdlib.h>
#include <math.h>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_odeiv2.h>

/* The error code indicates how to pre-allocate memory
 * for output values such as `f_`. The _vf function returns
 * the number of state variables, if any of the args are `NULL`.
 * evaluation errors can be indicated by negative return values.
 * GSL_SUCCESS (0) is returned when no error occurred.
 */

/* ode vector field: y'=f(t,y;p), the Activation expression is currently unused */
int AKAP79_vf(double t, const double y_[], double f_[], void *par)
{
	double *p_=par;
	if (!y_ || !f_) return 16;
	double kf_Rii_C__RiiP_C=p_[0];
	double kf_RiiP_CxcAMP__RiiP_C_cAMP=p_[1];
	double kf_RiiP_cAMPxC__RiiP_C_cAMP=p_[2];
	double kb_RiiP_cAMPxC__RiiP_C_cAMP=p_[3];
	double kb_RiiPXcAMP__RiiP_cAMP=p_[4];
	double kf_RiiPXcAMP__RiiP_cAMP=p_[5];
	double kf_RiiPxC__RiiP_C=p_[6];
	double kb_RiiPxC__RiiP_C=p_[7];
	double kf_cAMPxRii__Rii_cAMP=p_[8];
	double kb_cAMPxRii__Rii_cAMP=p_[9];
	double kf_Rii_CxcAMP__Rii_C_cAMP=p_[10];
	double kb_Rii_CxcAMP__Rii_C_cAMP=p_[11];
	double kf_RiixC__Rii_C=p_[12];
	double kf_Rii_cAMPxC__Rii_C_cAMP=p_[13];
	double kb_Rii_cAMPxC__Rii_C_cAMP=p_[14];
	double kf_Rii_C_cAMP__RiiP_C_cAMP=p_[15];
	double kb_RiixC__Rii_C=p_[16];
	double AKAPoff_1=p_[17];
	double AKAPoff_3=p_[18];
	double AKAPon_1=p_[19];
	double AKAPon_3=p_[20];
	double kf_C_AKAR4=p_[21];
	double kb_C_AKAR4=p_[22];
	double kcat_AKARp=p_[23];
	double kmOFF=p_[24];
	double kmON=p_[25];
	double KD_T=p_[26];
	double b_AKAP=p_[27];
	double Rii=y_[0];
	double cAMP=y_[1];
	double RiiP=y_[2];
	double Rii_C=y_[3];
	double RiiP_cAMP=y_[4];
	double RiiP_C=y_[5];
	double RiiP_C_cAMP=y_[6];
	double C=y_[7];
	double Rii_cAMP=y_[8];
	double Rii_C_cAMP=y_[9];
	double CaN=y_[10];
	double RiiP_CaN=y_[11];
	double RiiP_cAMP_CaN=y_[12];
	double AKAR4=y_[13];
	double AKAR4_C=y_[14];
	double AKAR4p=y_[15];
	double kf_RiiP_cAMP_CaN__CaNXRii_cAMP=b_AKAP * AKAPon_1 + (1 - b_AKAP) * AKAPoff_1;
	double kb_RiiPxCaN__RiiP_CaN=b_AKAP*AKAPon_3  +  (1 - b_AKAP)* AKAPoff_3;
	double kf_RiiP_CaN__RiixCaN=b_AKAP * AKAPon_1 + (1 - b_AKAP) * AKAPoff_1;
	double kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN=b_AKAP*AKAPon_3  +  (1 - b_AKAP)* AKAPoff_3;
	double kf_RiiPxCaN__RiiP_CaN=b_AKAP * ((kb_RiiPxCaN__RiiP_CaN + kf_RiiP_cAMP_CaN__CaNXRii_cAMP)/kmON ) + (1 - b_AKAP) * (kb_RiiPxCaN__RiiP_CaN + kf_RiiP_cAMP_CaN__CaNXRii_cAMP) / kmOFF;
	double kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN=b_AKAP * ((kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN + kf_RiiP_CaN__RiixCaN)/kmON) + (1 - b_AKAP) * (kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN + kf_RiiP_CaN__RiixCaN)/kmOFF;
	double kb_RiiP_CxcAMP__RiiP_C_cAMP=kf_RiiP_CxcAMP__RiiP_C_cAMP * KD_T;
	double reaction_51=kf_Rii_C__RiiP_C*Rii_C;
	double reaction_14=kf_RiiPxC__RiiP_C*RiiP*C - kb_RiiPxC__RiiP_C*RiiP_C;
	double reaction_12=kf_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C*cAMP - kb_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C_cAMP;
	double reaction_43=kf_RiiPXcAMP__RiiP_cAMP*cAMP*RiiP - kb_RiiPXcAMP__RiiP_cAMP*RiiP_cAMP;
	double reaction_23=kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP*C - kb_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_C_cAMP;
	double reaction_78=kf_cAMPxRii__Rii_cAMP*cAMP*Rii - kb_cAMPxRii__Rii_cAMP*Rii_cAMP;
	double reaction_56=kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C*cAMP - kb_Rii_CxcAMP__Rii_C_cAMP*Rii_C_cAMP;
	double reaction_76=kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP*C - kb_Rii_cAMPxC__Rii_C_cAMP*Rii_C_cAMP;
	double reaction_62=kf_Rii_C_cAMP__RiiP_C_cAMP*Rii_C_cAMP;
	double reaction_58=kf_RiixC__Rii_C*Rii*C - kb_RiixC__Rii_C*Rii_C;
	double reaction_44_=kf_RiiPxCaN__RiiP_CaN*RiiP*CaN - kb_RiiPxCaN__RiiP_CaN*RiiP_CaN;
	double reaction_33_=kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*CaN*RiiP_cAMP - kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP_CaN;
	double reaction_4_8=kf_RiiP_CaN__RiixCaN*RiiP_CaN;
	double reaction_3_7=kf_RiiP_cAMP_CaN__CaNXRii_cAMP*RiiP_cAMP_CaN;
	double reaction_1=kf_C_AKAR4*C*AKAR4 - kb_C_AKAR4*AKAR4_C;
	double reaction_2=kcat_AKARp*AKAR4_C;
	f_[0] = -reaction_78-reaction_58+reaction_4_8;
	f_[1] = -reaction_12-reaction_43-reaction_78-reaction_56;
	f_[2] = -reaction_14-reaction_43-reaction_44_;
	f_[3] = -reaction_51-reaction_56+reaction_58;
	f_[4] = +reaction_43-reaction_23-reaction_33_;
	f_[5] = +reaction_51+reaction_14-reaction_12;
	f_[6] = +reaction_12+reaction_23+reaction_62;
	f_[7] = -reaction_14-reaction_23-reaction_76-reaction_58-reaction_1+reaction_2;
	f_[8] = +reaction_78-reaction_76+reaction_3_7;
	f_[9] = +reaction_56+reaction_76-reaction_62;
	f_[10] = -reaction_44_-reaction_33_+reaction_4_8+reaction_3_7;
	f_[11] = +reaction_44_-reaction_4_8;
	f_[12] = +reaction_33_-reaction_3_7;
	f_[13] = -reaction_1;
	f_[14] = +reaction_1-reaction_2;
	f_[15] = +reaction_2;
	return GSL_SUCCESS;
}
/* ode Jacobian df(t,y;p)/dy */
int AKAP79_jac(double t, const double y_[], double *jac_, double *dfdt_, void *par)
{
	double *p_=par;
	if (!y_ || !jac_) return 16*16;
	double kf_Rii_C__RiiP_C=p_[0];
	double kf_RiiP_CxcAMP__RiiP_C_cAMP=p_[1];
	double kf_RiiP_cAMPxC__RiiP_C_cAMP=p_[2];
	double kb_RiiP_cAMPxC__RiiP_C_cAMP=p_[3];
	double kb_RiiPXcAMP__RiiP_cAMP=p_[4];
	double kf_RiiPXcAMP__RiiP_cAMP=p_[5];
	double kf_RiiPxC__RiiP_C=p_[6];
	double kb_RiiPxC__RiiP_C=p_[7];
	double kf_cAMPxRii__Rii_cAMP=p_[8];
	double kb_cAMPxRii__Rii_cAMP=p_[9];
	double kf_Rii_CxcAMP__Rii_C_cAMP=p_[10];
	double kb_Rii_CxcAMP__Rii_C_cAMP=p_[11];
	double kf_RiixC__Rii_C=p_[12];
	double kf_Rii_cAMPxC__Rii_C_cAMP=p_[13];
	double kb_Rii_cAMPxC__Rii_C_cAMP=p_[14];
	double kf_Rii_C_cAMP__RiiP_C_cAMP=p_[15];
	double kb_RiixC__Rii_C=p_[16];
	double AKAPoff_1=p_[17];
	double AKAPoff_3=p_[18];
	double AKAPon_1=p_[19];
	double AKAPon_3=p_[20];
	double kf_C_AKAR4=p_[21];
	double kb_C_AKAR4=p_[22];
	double kcat_AKARp=p_[23];
	double kmOFF=p_[24];
	double kmON=p_[25];
	double KD_T=p_[26];
	double b_AKAP=p_[27];
	double Rii=y_[0];
	double cAMP=y_[1];
	double RiiP=y_[2];
	double Rii_C=y_[3];
	double RiiP_cAMP=y_[4];
	double RiiP_C=y_[5];
	double RiiP_C_cAMP=y_[6];
	double C=y_[7];
	double Rii_cAMP=y_[8];
	double Rii_C_cAMP=y_[9];
	double CaN=y_[10];
	double RiiP_CaN=y_[11];
	double RiiP_cAMP_CaN=y_[12];
	double AKAR4=y_[13];
	double AKAR4_C=y_[14];
	double AKAR4p=y_[15];
	double kf_RiiP_cAMP_CaN__CaNXRii_cAMP=b_AKAP * AKAPon_1 + (1 - b_AKAP) * AKAPoff_1;
	double kb_RiiPxCaN__RiiP_CaN=b_AKAP*AKAPon_3  +  (1 - b_AKAP)* AKAPoff_3;
	double kf_RiiP_CaN__RiixCaN=b_AKAP * AKAPon_1 + (1 - b_AKAP) * AKAPoff_1;
	double kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN=b_AKAP*AKAPon_3  +  (1 - b_AKAP)* AKAPoff_3;
	double kf_RiiPxCaN__RiiP_CaN=b_AKAP * ((kb_RiiPxCaN__RiiP_CaN + kf_RiiP_cAMP_CaN__CaNXRii_cAMP)/kmON ) + (1 - b_AKAP) * (kb_RiiPxCaN__RiiP_CaN + kf_RiiP_cAMP_CaN__CaNXRii_cAMP) / kmOFF;
	double kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN=b_AKAP * ((kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN + kf_RiiP_CaN__RiixCaN)/kmON) + (1 - b_AKAP) * (kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN + kf_RiiP_CaN__RiixCaN)/kmOFF;
	double kb_RiiP_CxcAMP__RiiP_C_cAMP=kf_RiiP_CxcAMP__RiiP_C_cAMP * KD_T;
	double reaction_51=kf_Rii_C__RiiP_C*Rii_C;
	double reaction_14=kf_RiiPxC__RiiP_C*RiiP*C - kb_RiiPxC__RiiP_C*RiiP_C;
	double reaction_12=kf_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C*cAMP - kb_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C_cAMP;
	double reaction_43=kf_RiiPXcAMP__RiiP_cAMP*cAMP*RiiP - kb_RiiPXcAMP__RiiP_cAMP*RiiP_cAMP;
	double reaction_23=kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP*C - kb_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_C_cAMP;
	double reaction_78=kf_cAMPxRii__Rii_cAMP*cAMP*Rii - kb_cAMPxRii__Rii_cAMP*Rii_cAMP;
	double reaction_56=kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C*cAMP - kb_Rii_CxcAMP__Rii_C_cAMP*Rii_C_cAMP;
	double reaction_76=kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP*C - kb_Rii_cAMPxC__Rii_C_cAMP*Rii_C_cAMP;
	double reaction_62=kf_Rii_C_cAMP__RiiP_C_cAMP*Rii_C_cAMP;
	double reaction_58=kf_RiixC__Rii_C*Rii*C - kb_RiixC__Rii_C*Rii_C;
	double reaction_44_=kf_RiiPxCaN__RiiP_CaN*RiiP*CaN - kb_RiiPxCaN__RiiP_CaN*RiiP_CaN;
	double reaction_33_=kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*CaN*RiiP_cAMP - kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP_CaN;
	double reaction_4_8=kf_RiiP_CaN__RiixCaN*RiiP_CaN;
	double reaction_3_7=kf_RiiP_cAMP_CaN__CaNXRii_cAMP*RiiP_cAMP_CaN;
	double reaction_1=kf_C_AKAR4*C*AKAR4 - kb_C_AKAR4*AKAR4_C;
	double reaction_2=kcat_AKARp*AKAR4_C;
/* column 1 (df/dy_0) */
	jac_[0] = ((0-(kf_cAMPxRii__Rii_cAMP*cAMP))-(kf_RiixC__Rii_C*C));
	jac_[16] = (kf_RiixC__Rii_C*C);
	jac_[32] = (kf_cAMPxRii__Rii_cAMP*cAMP);
	jac_[48] = 0;
	jac_[64] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[80] = ((0*RiiP)*CaN);
	jac_[96] = ((0*CaN)*RiiP_cAMP);
	jac_[112] = 0;
	jac_[128] = 0;
	jac_[144] = 0;
/* column 2 (df/dy_1) */
	jac_[1] = (0-(kf_cAMPxRii__Rii_cAMP*Rii));
	jac_[17] = (0-(kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C));
	jac_[33] = (kf_cAMPxRii__Rii_cAMP*Rii);
	jac_[49] = (kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C);
	jac_[65] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[81] = ((0*RiiP)*CaN);
	jac_[97] = ((0*CaN)*RiiP_cAMP);
	jac_[113] = 0;
	jac_[129] = 0;
	jac_[145] = 0;
/* column 3 (df/dy_2) */
	jac_[2] = 0;
	jac_[18] = 0;
	jac_[34] = 0;
	jac_[50] = 0;
	jac_[66] = ((0-(((0*RiiP)+((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))))*CaN))-((0*CaN)*RiiP_cAMP));
	jac_[82] = (((0*RiiP)+((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))))*CaN);
	jac_[98] = ((0*CaN)*RiiP_cAMP);
	jac_[114] = 0;
	jac_[130] = 0;
	jac_[146] = 0;
/* column 4 (df/dy_3) */
	jac_[3] = (0-(0-kb_RiixC__Rii_C));
	jac_[19] = (((0-kf_Rii_C__RiiP_C)-(kf_Rii_CxcAMP__Rii_C_cAMP*cAMP))+(0-kb_RiixC__Rii_C));
	jac_[35] = 0;
	jac_[51] = (kf_Rii_CxcAMP__Rii_C_cAMP*cAMP);
	jac_[67] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[83] = ((0*RiiP)*CaN);
	jac_[99] = ((0*CaN)*RiiP_cAMP);
	jac_[115] = 0;
	jac_[131] = 0;
	jac_[147] = 0;
/* column 5 (df/dy_4) */
	jac_[4] = 0;
	jac_[20] = 0;
	jac_[36] = 0;
	jac_[52] = 0;
	jac_[68] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-(CaN*((0*RiiP_cAMP)+((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))))));
	jac_[84] = ((0*RiiP)*CaN);
	jac_[100] = (CaN*((0*RiiP_cAMP)+((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF)))));
	jac_[116] = 0;
	jac_[132] = 0;
	jac_[148] = 0;
/* column 6 (df/dy_5) */
	jac_[5] = 0;
	jac_[21] = 0;
	jac_[37] = 0;
	jac_[53] = 0;
	jac_[69] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[85] = ((0*RiiP)*CaN);
	jac_[101] = ((0*CaN)*RiiP_cAMP);
	jac_[117] = 0;
	jac_[133] = 0;
	jac_[149] = 0;
/* column 7 (df/dy_6) */
	jac_[6] = 0;
	jac_[22] = 0;
	jac_[38] = 0;
	jac_[54] = 0;
	jac_[70] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[86] = ((0*RiiP)*CaN);
	jac_[102] = ((0*CaN)*RiiP_cAMP);
	jac_[118] = 0;
	jac_[134] = 0;
	jac_[150] = 0;
/* column 8 (df/dy_7) */
	jac_[7] = (0-(kf_RiixC__Rii_C*Rii));
	jac_[23] = (kf_RiixC__Rii_C*Rii);
	jac_[39] = (0-(kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP));
	jac_[55] = (kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP);
	jac_[71] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[87] = ((0*RiiP)*CaN);
	jac_[103] = ((0*CaN)*RiiP_cAMP);
	jac_[119] = (0-(kf_C_AKAR4*AKAR4));
	jac_[135] = (kf_C_AKAR4*AKAR4);
	jac_[151] = 0;
/* column 9 (df/dy_8) */
	jac_[8] = (0-(0-kb_cAMPxRii__Rii_cAMP));
	jac_[24] = 0;
	jac_[40] = ((0-kb_cAMPxRii__Rii_cAMP)-(kf_Rii_cAMPxC__Rii_C_cAMP*C));
	jac_[56] = (kf_Rii_cAMPxC__Rii_C_cAMP*C);
	jac_[72] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[88] = ((0*RiiP)*CaN);
	jac_[104] = ((0*CaN)*RiiP_cAMP);
	jac_[120] = 0;
	jac_[136] = 0;
	jac_[152] = 0;
/* column 10 (df/dy_9) */
	jac_[9] = 0;
	jac_[25] = (0-(0-kb_Rii_CxcAMP__Rii_C_cAMP));
	jac_[41] = (0-(0-kb_Rii_cAMPxC__Rii_C_cAMP));
	jac_[57] = (((0-kb_Rii_CxcAMP__Rii_C_cAMP)+(0-kb_Rii_cAMPxC__Rii_C_cAMP))-kf_Rii_C_cAMP__RiiP_C_cAMP);
	jac_[73] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[89] = ((0*RiiP)*CaN);
	jac_[105] = ((0*CaN)*RiiP_cAMP);
	jac_[121] = 0;
	jac_[137] = 0;
	jac_[153] = 0;
/* column 11 (df/dy_10) */
	jac_[10] = 0;
	jac_[26] = 0;
	jac_[42] = 0;
	jac_[58] = 0;
	jac_[74] = ((0-(RiiP*((0*CaN)+((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))))))-(((0*CaN)+((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))))*RiiP_cAMP));
	jac_[90] = (RiiP*((0*CaN)+((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF)))));
	jac_[106] = (((0*CaN)+((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))))*RiiP_cAMP);
	jac_[122] = 0;
	jac_[138] = 0;
	jac_[154] = 0;
/* column 12 (df/dy_11) */
	jac_[11] = ((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1));
	jac_[27] = 0;
	jac_[43] = 0;
	jac_[59] = 0;
	jac_[75] = (((0-(((0*RiiP)*CaN)-((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))))-((0*CaN)*RiiP_cAMP))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)));
	jac_[91] = ((((0*RiiP)*CaN)-((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3)))-((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)));
	jac_[107] = ((0*CaN)*RiiP_cAMP);
	jac_[123] = 0;
	jac_[139] = 0;
	jac_[155] = 0;
/* column 13 (df/dy_12) */
	jac_[12] = 0;
	jac_[28] = 0;
	jac_[44] = ((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1));
	jac_[60] = 0;
	jac_[76] = (((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-(((0*CaN)*RiiP_cAMP)-((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)));
	jac_[92] = ((0*RiiP)*CaN);
	jac_[108] = ((((0*CaN)*RiiP_cAMP)-((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3)))-((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)));
	jac_[124] = 0;
	jac_[140] = 0;
	jac_[156] = 0;
/* column 14 (df/dy_13) */
	jac_[13] = 0;
	jac_[29] = 0;
	jac_[45] = 0;
	jac_[61] = 0;
	jac_[77] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[93] = ((0*RiiP)*CaN);
	jac_[109] = ((0*CaN)*RiiP_cAMP);
	jac_[125] = (0-(kf_C_AKAR4*C));
	jac_[141] = (kf_C_AKAR4*C);
	jac_[157] = 0;
/* column 15 (df/dy_14) */
	jac_[14] = 0;
	jac_[30] = 0;
	jac_[46] = 0;
	jac_[62] = 0;
	jac_[78] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[94] = ((0*RiiP)*CaN);
	jac_[110] = ((0*CaN)*RiiP_cAMP);
	jac_[126] = (0-(0-kb_C_AKAR4));
	jac_[142] = ((0-kb_C_AKAR4)-kcat_AKARp);
	jac_[158] = kcat_AKARp;
/* column 16 (df/dy_15) */
	jac_[15] = 0;
	jac_[31] = 0;
	jac_[47] = 0;
	jac_[63] = 0;
	jac_[79] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jac_[95] = ((0*RiiP)*CaN);
	jac_[111] = ((0*CaN)*RiiP_cAMP);
	jac_[127] = 0;
	jac_[143] = 0;
	jac_[159] = 0;
	return GSL_SUCCESS;
}
/* ode parameter Jacobian df(t,y;p)/dp */
int AKAP79_jacp(double t, const double y_[], double *jacp_, double *dfdt_, void *par)
{
	double *p_=par;
	if (!y_ || !jacp_) return 16*28;
	double kf_Rii_C__RiiP_C=p_[0];
	double kf_RiiP_CxcAMP__RiiP_C_cAMP=p_[1];
	double kf_RiiP_cAMPxC__RiiP_C_cAMP=p_[2];
	double kb_RiiP_cAMPxC__RiiP_C_cAMP=p_[3];
	double kb_RiiPXcAMP__RiiP_cAMP=p_[4];
	double kf_RiiPXcAMP__RiiP_cAMP=p_[5];
	double kf_RiiPxC__RiiP_C=p_[6];
	double kb_RiiPxC__RiiP_C=p_[7];
	double kf_cAMPxRii__Rii_cAMP=p_[8];
	double kb_cAMPxRii__Rii_cAMP=p_[9];
	double kf_Rii_CxcAMP__Rii_C_cAMP=p_[10];
	double kb_Rii_CxcAMP__Rii_C_cAMP=p_[11];
	double kf_RiixC__Rii_C=p_[12];
	double kf_Rii_cAMPxC__Rii_C_cAMP=p_[13];
	double kb_Rii_cAMPxC__Rii_C_cAMP=p_[14];
	double kf_Rii_C_cAMP__RiiP_C_cAMP=p_[15];
	double kb_RiixC__Rii_C=p_[16];
	double AKAPoff_1=p_[17];
	double AKAPoff_3=p_[18];
	double AKAPon_1=p_[19];
	double AKAPon_3=p_[20];
	double kf_C_AKAR4=p_[21];
	double kb_C_AKAR4=p_[22];
	double kcat_AKARp=p_[23];
	double kmOFF=p_[24];
	double kmON=p_[25];
	double KD_T=p_[26];
	double b_AKAP=p_[27];
	double Rii=y_[0];
	double cAMP=y_[1];
	double RiiP=y_[2];
	double Rii_C=y_[3];
	double RiiP_cAMP=y_[4];
	double RiiP_C=y_[5];
	double RiiP_C_cAMP=y_[6];
	double C=y_[7];
	double Rii_cAMP=y_[8];
	double Rii_C_cAMP=y_[9];
	double CaN=y_[10];
	double RiiP_CaN=y_[11];
	double RiiP_cAMP_CaN=y_[12];
	double AKAR4=y_[13];
	double AKAR4_C=y_[14];
	double AKAR4p=y_[15];
	double kf_RiiP_cAMP_CaN__CaNXRii_cAMP=b_AKAP * AKAPon_1 + (1 - b_AKAP) * AKAPoff_1;
	double kb_RiiPxCaN__RiiP_CaN=b_AKAP*AKAPon_3  +  (1 - b_AKAP)* AKAPoff_3;
	double kf_RiiP_CaN__RiixCaN=b_AKAP * AKAPon_1 + (1 - b_AKAP) * AKAPoff_1;
	double kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN=b_AKAP*AKAPon_3  +  (1 - b_AKAP)* AKAPoff_3;
	double kf_RiiPxCaN__RiiP_CaN=b_AKAP * ((kb_RiiPxCaN__RiiP_CaN + kf_RiiP_cAMP_CaN__CaNXRii_cAMP)/kmON ) + (1 - b_AKAP) * (kb_RiiPxCaN__RiiP_CaN + kf_RiiP_cAMP_CaN__CaNXRii_cAMP) / kmOFF;
	double kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN=b_AKAP * ((kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN + kf_RiiP_CaN__RiixCaN)/kmON) + (1 - b_AKAP) * (kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN + kf_RiiP_CaN__RiixCaN)/kmOFF;
	double kb_RiiP_CxcAMP__RiiP_C_cAMP=kf_RiiP_CxcAMP__RiiP_C_cAMP * KD_T;
	double reaction_51=kf_Rii_C__RiiP_C*Rii_C;
	double reaction_14=kf_RiiPxC__RiiP_C*RiiP*C - kb_RiiPxC__RiiP_C*RiiP_C;
	double reaction_12=kf_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C*cAMP - kb_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C_cAMP;
	double reaction_43=kf_RiiPXcAMP__RiiP_cAMP*cAMP*RiiP - kb_RiiPXcAMP__RiiP_cAMP*RiiP_cAMP;
	double reaction_23=kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP*C - kb_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_C_cAMP;
	double reaction_78=kf_cAMPxRii__Rii_cAMP*cAMP*Rii - kb_cAMPxRii__Rii_cAMP*Rii_cAMP;
	double reaction_56=kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C*cAMP - kb_Rii_CxcAMP__Rii_C_cAMP*Rii_C_cAMP;
	double reaction_76=kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP*C - kb_Rii_cAMPxC__Rii_C_cAMP*Rii_C_cAMP;
	double reaction_62=kf_Rii_C_cAMP__RiiP_C_cAMP*Rii_C_cAMP;
	double reaction_58=kf_RiixC__Rii_C*Rii*C - kb_RiixC__Rii_C*Rii_C;
	double reaction_44_=kf_RiiPxCaN__RiiP_CaN*RiiP*CaN - kb_RiiPxCaN__RiiP_CaN*RiiP_CaN;
	double reaction_33_=kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*CaN*RiiP_cAMP - kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP_CaN;
	double reaction_4_8=kf_RiiP_CaN__RiixCaN*RiiP_CaN;
	double reaction_3_7=kf_RiiP_cAMP_CaN__CaNXRii_cAMP*RiiP_cAMP_CaN;
	double reaction_1=kf_C_AKAR4*C*AKAR4 - kb_C_AKAR4*AKAR4_C;
	double reaction_2=kcat_AKARp*AKAR4_C;
/* column 1 (df/dp_0) */
	jacp_[0] = 0;
	jacp_[28] = (0-Rii_C);
	jacp_[56] = 0;
	jacp_[84] = 0;
	jacp_[112] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[140] = ((0*RiiP)*CaN);
	jacp_[168] = ((0*CaN)*RiiP_cAMP);
	jacp_[196] = 0;
	jacp_[224] = 0;
	jacp_[252] = 0;
/* column 2 (df/dp_1) */
	jacp_[1] = 0;
	jacp_[29] = 0;
	jacp_[57] = 0;
	jacp_[85] = 0;
	jacp_[113] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[141] = ((0*RiiP)*CaN);
	jacp_[169] = ((0*CaN)*RiiP_cAMP);
	jacp_[197] = 0;
	jacp_[225] = 0;
	jacp_[253] = 0;
/* column 3 (df/dp_2) */
	jacp_[2] = 0;
	jacp_[30] = 0;
	jacp_[58] = 0;
	jacp_[86] = 0;
	jacp_[114] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[142] = ((0*RiiP)*CaN);
	jacp_[170] = ((0*CaN)*RiiP_cAMP);
	jacp_[198] = 0;
	jacp_[226] = 0;
	jacp_[254] = 0;
/* column 4 (df/dp_3) */
	jacp_[3] = 0;
	jacp_[31] = 0;
	jacp_[59] = 0;
	jacp_[87] = 0;
	jacp_[115] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[143] = ((0*RiiP)*CaN);
	jacp_[171] = ((0*CaN)*RiiP_cAMP);
	jacp_[199] = 0;
	jacp_[227] = 0;
	jacp_[255] = 0;
/* column 5 (df/dp_4) */
	jacp_[4] = 0;
	jacp_[32] = 0;
	jacp_[60] = 0;
	jacp_[88] = 0;
	jacp_[116] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[144] = ((0*RiiP)*CaN);
	jacp_[172] = ((0*CaN)*RiiP_cAMP);
	jacp_[200] = 0;
	jacp_[228] = 0;
	jacp_[256] = 0;
/* column 6 (df/dp_5) */
	jacp_[5] = 0;
	jacp_[33] = 0;
	jacp_[61] = 0;
	jacp_[89] = 0;
	jacp_[117] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[145] = ((0*RiiP)*CaN);
	jacp_[173] = ((0*CaN)*RiiP_cAMP);
	jacp_[201] = 0;
	jacp_[229] = 0;
	jacp_[257] = 0;
/* column 7 (df/dp_6) */
	jacp_[6] = 0;
	jacp_[34] = 0;
	jacp_[62] = 0;
	jacp_[90] = 0;
	jacp_[118] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[146] = ((0*RiiP)*CaN);
	jacp_[174] = ((0*CaN)*RiiP_cAMP);
	jacp_[202] = 0;
	jacp_[230] = 0;
	jacp_[258] = 0;
/* column 8 (df/dp_7) */
	jacp_[7] = 0;
	jacp_[35] = 0;
	jacp_[63] = 0;
	jacp_[91] = 0;
	jacp_[119] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[147] = ((0*RiiP)*CaN);
	jacp_[175] = ((0*CaN)*RiiP_cAMP);
	jacp_[203] = 0;
	jacp_[231] = 0;
	jacp_[259] = 0;
/* column 9 (df/dp_8) */
	jacp_[8] = (0-(cAMP*Rii));
	jacp_[36] = 0;
	jacp_[64] = (cAMP*Rii);
	jacp_[92] = 0;
	jacp_[120] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[148] = ((0*RiiP)*CaN);
	jacp_[176] = ((0*CaN)*RiiP_cAMP);
	jacp_[204] = 0;
	jacp_[232] = 0;
	jacp_[260] = 0;
/* column 10 (df/dp_9) */
	jacp_[9] = (0-(0-Rii_cAMP));
	jacp_[37] = 0;
	jacp_[65] = (0-Rii_cAMP);
	jacp_[93] = 0;
	jacp_[121] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[149] = ((0*RiiP)*CaN);
	jacp_[177] = ((0*CaN)*RiiP_cAMP);
	jacp_[205] = 0;
	jacp_[233] = 0;
	jacp_[261] = 0;
/* column 11 (df/dp_10) */
	jacp_[10] = 0;
	jacp_[38] = (0-(Rii_C*cAMP));
	jacp_[66] = 0;
	jacp_[94] = (Rii_C*cAMP);
	jacp_[122] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[150] = ((0*RiiP)*CaN);
	jacp_[178] = ((0*CaN)*RiiP_cAMP);
	jacp_[206] = 0;
	jacp_[234] = 0;
	jacp_[262] = 0;
/* column 12 (df/dp_11) */
	jacp_[11] = 0;
	jacp_[39] = (0-(0-Rii_C_cAMP));
	jacp_[67] = 0;
	jacp_[95] = (0-Rii_C_cAMP);
	jacp_[123] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[151] = ((0*RiiP)*CaN);
	jacp_[179] = ((0*CaN)*RiiP_cAMP);
	jacp_[207] = 0;
	jacp_[235] = 0;
	jacp_[263] = 0;
/* column 13 (df/dp_12) */
	jacp_[12] = (0-(Rii*C));
	jacp_[40] = (Rii*C);
	jacp_[68] = 0;
	jacp_[96] = 0;
	jacp_[124] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[152] = ((0*RiiP)*CaN);
	jacp_[180] = ((0*CaN)*RiiP_cAMP);
	jacp_[208] = 0;
	jacp_[236] = 0;
	jacp_[264] = 0;
/* column 14 (df/dp_13) */
	jacp_[13] = 0;
	jacp_[41] = 0;
	jacp_[69] = (0-(Rii_cAMP*C));
	jacp_[97] = (Rii_cAMP*C);
	jacp_[125] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[153] = ((0*RiiP)*CaN);
	jacp_[181] = ((0*CaN)*RiiP_cAMP);
	jacp_[209] = 0;
	jacp_[237] = 0;
	jacp_[265] = 0;
/* column 15 (df/dp_14) */
	jacp_[14] = 0;
	jacp_[42] = 0;
	jacp_[70] = (0-(0-Rii_C_cAMP));
	jacp_[98] = (0-Rii_C_cAMP);
	jacp_[126] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[154] = ((0*RiiP)*CaN);
	jacp_[182] = ((0*CaN)*RiiP_cAMP);
	jacp_[210] = 0;
	jacp_[238] = 0;
	jacp_[266] = 0;
/* column 16 (df/dp_15) */
	jacp_[15] = 0;
	jacp_[43] = 0;
	jacp_[71] = 0;
	jacp_[99] = (0-Rii_C_cAMP);
	jacp_[127] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[155] = ((0*RiiP)*CaN);
	jacp_[183] = ((0*CaN)*RiiP_cAMP);
	jacp_[211] = 0;
	jacp_[239] = 0;
	jacp_[267] = 0;
/* column 17 (df/dp_16) */
	jacp_[16] = (0-(0-Rii_C));
	jacp_[44] = (0-Rii_C);
	jacp_[72] = 0;
	jacp_[100] = 0;
	jacp_[128] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[156] = ((0*RiiP)*CaN);
	jacp_[184] = ((0*CaN)*RiiP_cAMP);
	jacp_[212] = 0;
	jacp_[240] = 0;
	jacp_[268] = 0;
/* column 18 (df/dp_17) */
	jacp_[17] = ((1-b_AKAP)*RiiP_CaN);
	jacp_[45] = 0;
	jacp_[73] = ((1-b_AKAP)*RiiP_cAMP_CaN);
	jacp_[101] = 0;
	jacp_[129] = ((((0-((((1-b_AKAP)*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF)))*RiiP)*CaN))-((((1-b_AKAP)*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF)))*CaN)*RiiP_cAMP))+((1-b_AKAP)*RiiP_CaN))+((1-b_AKAP)*RiiP_cAMP_CaN));
	jacp_[157] = ((1-b_AKAP)*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*RiiP)*CaN)-RiiP_CaN));
	jacp_[185] = ((1-b_AKAP)*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*CaN)*RiiP_cAMP)-RiiP_cAMP_CaN));
	jacp_[213] = 0;
	jacp_[241] = 0;
	jacp_[269] = 0;
/* column 19 (df/dp_18) */
	jacp_[18] = 0;
	jacp_[46] = 0;
	jacp_[74] = 0;
	jacp_[102] = 0;
	jacp_[130] = ((0-((1-b_AKAP)*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*RiiP)*CaN)-RiiP_CaN)))-((1-b_AKAP)*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*CaN)*RiiP_cAMP)-RiiP_cAMP_CaN)));
	jacp_[158] = ((1-b_AKAP)*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*RiiP)*CaN)-RiiP_CaN));
	jacp_[186] = ((1-b_AKAP)*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*CaN)*RiiP_cAMP)-RiiP_cAMP_CaN));
	jacp_[214] = 0;
	jacp_[242] = 0;
	jacp_[270] = 0;
/* column 20 (df/dp_19) */
	jacp_[19] = (b_AKAP*RiiP_CaN);
	jacp_[47] = 0;
	jacp_[75] = (b_AKAP*RiiP_cAMP_CaN);
	jacp_[103] = 0;
	jacp_[131] = ((((0-(((b_AKAP*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF)))*RiiP)*CaN))-(((b_AKAP*((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF)))*CaN)*RiiP_cAMP))+(b_AKAP*RiiP_CaN))+(b_AKAP*RiiP_cAMP_CaN));
	jacp_[159] = (b_AKAP*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*RiiP)*CaN)-RiiP_CaN));
	jacp_[187] = (b_AKAP*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*CaN)*RiiP_cAMP)-RiiP_cAMP_CaN));
	jacp_[215] = 0;
	jacp_[243] = 0;
	jacp_[271] = 0;
/* column 21 (df/dp_20) */
	jacp_[20] = 0;
	jacp_[48] = 0;
	jacp_[76] = 0;
	jacp_[104] = 0;
	jacp_[132] = ((0-(b_AKAP*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*RiiP)*CaN)-RiiP_CaN)))-(b_AKAP*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*CaN)*RiiP_cAMP)-RiiP_cAMP_CaN)));
	jacp_[160] = (b_AKAP*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*RiiP)*CaN)-RiiP_CaN));
	jacp_[188] = (b_AKAP*(((((b_AKAP*(1/kmON))+((1-b_AKAP)/kmOFF))*CaN)*RiiP_cAMP)-RiiP_cAMP_CaN));
	jacp_[216] = 0;
	jacp_[244] = 0;
	jacp_[272] = 0;
/* column 22 (df/dp_21) */
	jacp_[21] = 0;
	jacp_[49] = 0;
	jacp_[77] = 0;
	jacp_[105] = 0;
	jacp_[133] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[161] = ((0*RiiP)*CaN);
	jacp_[189] = ((0*CaN)*RiiP_cAMP);
	jacp_[217] = (0-(C*AKAR4));
	jacp_[245] = (C*AKAR4);
	jacp_[273] = 0;
/* column 23 (df/dp_22) */
	jacp_[22] = 0;
	jacp_[50] = 0;
	jacp_[78] = 0;
	jacp_[106] = 0;
	jacp_[134] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[162] = ((0*RiiP)*CaN);
	jacp_[190] = ((0*CaN)*RiiP_cAMP);
	jacp_[218] = (0-(0-AKAR4_C));
	jacp_[246] = (0-AKAR4_C);
	jacp_[274] = 0;
/* column 24 (df/dp_23) */
	jacp_[23] = 0;
	jacp_[51] = 0;
	jacp_[79] = 0;
	jacp_[107] = 0;
	jacp_[135] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[163] = ((0*RiiP)*CaN);
	jacp_[191] = ((0*CaN)*RiiP_cAMP);
	jacp_[219] = 0;
	jacp_[247] = (0-AKAR4_C);
	jacp_[275] = AKAR4_C;
/* column 25 (df/dp_24) */
	jacp_[24] = 0;
	jacp_[52] = 0;
	jacp_[80] = 0;
	jacp_[108] = 0;
	jacp_[136] = ((0-((((b_AKAP*0)+(((1-b_AKAP)*(0-(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))))/(kmOFF*kmOFF)))*RiiP)*CaN))-((((b_AKAP*0)+(((1-b_AKAP)*(0-(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))))/(kmOFF*kmOFF)))*CaN)*RiiP_cAMP));
	jacp_[164] = ((((b_AKAP*0)+(((1-b_AKAP)*(0-(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))))/(kmOFF*kmOFF)))*RiiP)*CaN);
	jacp_[192] = ((((b_AKAP*0)+(((1-b_AKAP)*(0-(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))))/(kmOFF*kmOFF)))*CaN)*RiiP_cAMP);
	jacp_[220] = 0;
	jacp_[248] = 0;
	jacp_[276] = 0;
/* column 26 (df/dp_25) */
	jacp_[25] = 0;
	jacp_[53] = 0;
	jacp_[81] = 0;
	jacp_[109] = 0;
	jacp_[137] = ((0-((((b_AKAP*((0-(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1))))/(kmON*kmON)))+(0/kmOFF))*RiiP)*CaN))-((((b_AKAP*((0-(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1))))/(kmON*kmON)))+(0/kmOFF))*CaN)*RiiP_cAMP));
	jacp_[165] = ((((b_AKAP*((0-(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1))))/(kmON*kmON)))+(0/kmOFF))*RiiP)*CaN);
	jacp_[193] = ((((b_AKAP*((0-(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1))))/(kmON*kmON)))+(0/kmOFF))*CaN)*RiiP_cAMP);
	jacp_[221] = 0;
	jacp_[249] = 0;
	jacp_[277] = 0;
/* column 27 (df/dp_26) */
	jacp_[26] = 0;
	jacp_[54] = 0;
	jacp_[82] = 0;
	jacp_[110] = 0;
	jacp_[138] = ((0*(1-(((1*((b_AKAP*((1*(1+1))/kmON))+(((1-b_AKAP)*(1*(1+1)))/kmOFF)))*RiiP)*CaN)))-((0*CaN)*RiiP_cAMP));
	jacp_[166] = ((0*RiiP)*CaN);
	jacp_[194] = ((0*CaN)*RiiP_cAMP);
	jacp_[222] = 0;
	jacp_[250] = 0;
	jacp_[278] = 0;
/* column 28 (df/dp_27) */
	jacp_[27] = ((AKAPon_1+(-1*AKAPoff_1))*RiiP_CaN);
	jacp_[55] = 0;
	jacp_[83] = ((AKAPon_1+(-1*AKAPoff_1))*RiiP_cAMP_CaN);
	jacp_[111] = 0;
	jacp_[139] = ((((0-(((((((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))/kmON)+(b_AKAP*(((AKAPon_3+(-1*AKAPoff_3))+(AKAPon_1+(-1*AKAPoff_1)))/kmON)))+(((-1*(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1))))+((1-b_AKAP)*((AKAPon_3+(-1*AKAPoff_3))+(AKAPon_1+(-1*AKAPoff_1)))))/kmOFF))*RiiP)*CaN)-((AKAPon_3+(-1*AKAPoff_3))*RiiP_CaN)))-(((((((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))/kmON)+(b_AKAP*(((AKAPon_3+(-1*AKAPoff_3))+(AKAPon_1+(-1*AKAPoff_1)))/kmON)))+(((-1*(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1))))+((1-b_AKAP)*((AKAPon_3+(-1*AKAPoff_3))+(AKAPon_1+(-1*AKAPoff_1)))))/kmOFF))*CaN)*RiiP_cAMP)-((AKAPon_3+(-1*AKAPoff_3))*RiiP_cAMP_CaN)))+((AKAPon_1+(-1*AKAPoff_1))*RiiP_CaN))+((AKAPon_1+(-1*AKAPoff_1))*RiiP_cAMP_CaN));
	jacp_[167] = ((((((((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))/kmON)+(b_AKAP*(((AKAPon_3+(-1*AKAPoff_3))+(AKAPon_1+(-1*AKAPoff_1)))/kmON)))+(((-1*(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1))))+((1-b_AKAP)*((AKAPon_3+(-1*AKAPoff_3))+(AKAPon_1+(-1*AKAPoff_1)))))/kmOFF))*RiiP)*CaN)-((AKAPon_3+(-1*AKAPoff_3))*RiiP_CaN))-((AKAPon_1+(-1*AKAPoff_1))*RiiP_CaN));
	jacp_[195] = ((((((((((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1)))/kmON)+(b_AKAP*(((AKAPon_3+(-1*AKAPoff_3))+(AKAPon_1+(-1*AKAPoff_1)))/kmON)))+(((-1*(((b_AKAP*AKAPon_3)+((1-b_AKAP)*AKAPoff_3))+((b_AKAP*AKAPon_1)+((1-b_AKAP)*AKAPoff_1))))+((1-b_AKAP)*((AKAPon_3+(-1*AKAPoff_3))+(AKAPon_1+(-1*AKAPoff_1)))))/kmOFF))*CaN)*RiiP_cAMP)-((AKAPon_3+(-1*AKAPoff_3))*RiiP_cAMP_CaN))-((AKAPon_1+(-1*AKAPoff_1))*RiiP_cAMP_CaN));
	jacp_[223] = 0;
	jacp_[251] = 0;
	jacp_[279] = 0;
	return GSL_SUCCESS;
}
/* ode Functions F(t,y;p) */
int AKAP79_func(double t, const double y_[], double *func_, void *par)
{
	double *p_=par;
	if (!y_ || !func_) return 1;
	double kf_Rii_C__RiiP_C=p_[0];
	double kf_RiiP_CxcAMP__RiiP_C_cAMP=p_[1];
	double kf_RiiP_cAMPxC__RiiP_C_cAMP=p_[2];
	double kb_RiiP_cAMPxC__RiiP_C_cAMP=p_[3];
	double kb_RiiPXcAMP__RiiP_cAMP=p_[4];
	double kf_RiiPXcAMP__RiiP_cAMP=p_[5];
	double kf_RiiPxC__RiiP_C=p_[6];
	double kb_RiiPxC__RiiP_C=p_[7];
	double kf_cAMPxRii__Rii_cAMP=p_[8];
	double kb_cAMPxRii__Rii_cAMP=p_[9];
	double kf_Rii_CxcAMP__Rii_C_cAMP=p_[10];
	double kb_Rii_CxcAMP__Rii_C_cAMP=p_[11];
	double kf_RiixC__Rii_C=p_[12];
	double kf_Rii_cAMPxC__Rii_C_cAMP=p_[13];
	double kb_Rii_cAMPxC__Rii_C_cAMP=p_[14];
	double kf_Rii_C_cAMP__RiiP_C_cAMP=p_[15];
	double kb_RiixC__Rii_C=p_[16];
	double AKAPoff_1=p_[17];
	double AKAPoff_3=p_[18];
	double AKAPon_1=p_[19];
	double AKAPon_3=p_[20];
	double kf_C_AKAR4=p_[21];
	double kb_C_AKAR4=p_[22];
	double kcat_AKARp=p_[23];
	double kmOFF=p_[24];
	double kmON=p_[25];
	double KD_T=p_[26];
	double b_AKAP=p_[27];
	double Rii=y_[0];
	double cAMP=y_[1];
	double RiiP=y_[2];
	double Rii_C=y_[3];
	double RiiP_cAMP=y_[4];
	double RiiP_C=y_[5];
	double RiiP_C_cAMP=y_[6];
	double C=y_[7];
	double Rii_cAMP=y_[8];
	double Rii_C_cAMP=y_[9];
	double CaN=y_[10];
	double RiiP_CaN=y_[11];
	double RiiP_cAMP_CaN=y_[12];
	double AKAR4=y_[13];
	double AKAR4_C=y_[14];
	double AKAR4p=y_[15];
	double kf_RiiP_cAMP_CaN__CaNXRii_cAMP=b_AKAP * AKAPon_1 + (1 - b_AKAP) * AKAPoff_1;
	double kb_RiiPxCaN__RiiP_CaN=b_AKAP*AKAPon_3  +  (1 - b_AKAP)* AKAPoff_3;
	double kf_RiiP_CaN__RiixCaN=b_AKAP * AKAPon_1 + (1 - b_AKAP) * AKAPoff_1;
	double kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN=b_AKAP*AKAPon_3  +  (1 - b_AKAP)* AKAPoff_3;
	double kf_RiiPxCaN__RiiP_CaN=b_AKAP * ((kb_RiiPxCaN__RiiP_CaN + kf_RiiP_cAMP_CaN__CaNXRii_cAMP)/kmON ) + (1 - b_AKAP) * (kb_RiiPxCaN__RiiP_CaN + kf_RiiP_cAMP_CaN__CaNXRii_cAMP) / kmOFF;
	double kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN=b_AKAP * ((kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN + kf_RiiP_CaN__RiixCaN)/kmON) + (1 - b_AKAP) * (kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN + kf_RiiP_CaN__RiixCaN)/kmOFF;
	double kb_RiiP_CxcAMP__RiiP_C_cAMP=kf_RiiP_CxcAMP__RiiP_C_cAMP * KD_T;
	double reaction_51=kf_Rii_C__RiiP_C*Rii_C;
	double reaction_14=kf_RiiPxC__RiiP_C*RiiP*C - kb_RiiPxC__RiiP_C*RiiP_C;
	double reaction_12=kf_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C*cAMP - kb_RiiP_CxcAMP__RiiP_C_cAMP*RiiP_C_cAMP;
	double reaction_43=kf_RiiPXcAMP__RiiP_cAMP*cAMP*RiiP - kb_RiiPXcAMP__RiiP_cAMP*RiiP_cAMP;
	double reaction_23=kf_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_cAMP*C - kb_RiiP_cAMPxC__RiiP_C_cAMP*RiiP_C_cAMP;
	double reaction_78=kf_cAMPxRii__Rii_cAMP*cAMP*Rii - kb_cAMPxRii__Rii_cAMP*Rii_cAMP;
	double reaction_56=kf_Rii_CxcAMP__Rii_C_cAMP*Rii_C*cAMP - kb_Rii_CxcAMP__Rii_C_cAMP*Rii_C_cAMP;
	double reaction_76=kf_Rii_cAMPxC__Rii_C_cAMP*Rii_cAMP*C - kb_Rii_cAMPxC__Rii_C_cAMP*Rii_C_cAMP;
	double reaction_62=kf_Rii_C_cAMP__RiiP_C_cAMP*Rii_C_cAMP;
	double reaction_58=kf_RiixC__Rii_C*Rii*C - kb_RiixC__Rii_C*Rii_C;
	double reaction_44_=kf_RiiPxCaN__RiiP_CaN*RiiP*CaN - kb_RiiPxCaN__RiiP_CaN*RiiP_CaN;
	double reaction_33_=kf_CaNxRiiP_cAMP__RiiP_cAMP_CaN*CaN*RiiP_cAMP - kb_CaNxRiiP_cAMP__RiiP_cAMP_CaN*RiiP_cAMP_CaN;
	double reaction_4_8=kf_RiiP_CaN__RiixCaN*RiiP_CaN;
	double reaction_3_7=kf_RiiP_cAMP_CaN__CaNXRii_cAMP*RiiP_cAMP_CaN;
	double reaction_1=kf_C_AKAR4*C*AKAR4 - kb_C_AKAR4*AKAR4_C;
	double reaction_2=kcat_AKARp*AKAR4_C;
	func_[0] = AKAR4p;
	return GSL_SUCCESS;
}
/* ode default parameters */
int AKAP79_default(double t, void *par)
{
	double *p_=par;
	if (!p_) return 28;
	p_[0] = 33;
	p_[1] = 0.496;
	p_[2] = 0.00545;
	p_[3] = 0.0156;
	p_[4] = 0.0016;
	p_[5] = 0.015;
	p_[6] = 0.038;
	p_[7] = 0.0026;
	p_[8] = 0.015;
	p_[9] = 0.0016;
	p_[10] = 0.496;
	p_[11] = 1.413;
	p_[12] = 2.1;
	p_[13] = 0.2984;
	p_[14] = 0.018;
	p_[15] = 33;
	p_[16] = 3e-04;
	p_[17] = 2.6;
	p_[18] = 20;
	p_[19] = 0.45;
	p_[20] = 2;
	p_[21] = 0.018;
	p_[22] = 0.106;
	p_[23] = 10.2;
	p_[24] = 100;
	p_[25] = 1;
	p_[26] = 0.7;
	p_[27] = 0;
	return GSL_SUCCESS;
}
/* ode initial values */
int AKAP79_init(double t, double *y_, void *par)
{
	double *p_=par;
	if (!y_) return 16;
	double kf_Rii_C__RiiP_C=p_[0];
	double kf_RiiP_CxcAMP__RiiP_C_cAMP=p_[1];
	double kf_RiiP_cAMPxC__RiiP_C_cAMP=p_[2];
	double kb_RiiP_cAMPxC__RiiP_C_cAMP=p_[3];
	double kb_RiiPXcAMP__RiiP_cAMP=p_[4];
	double kf_RiiPXcAMP__RiiP_cAMP=p_[5];
	double kf_RiiPxC__RiiP_C=p_[6];
	double kb_RiiPxC__RiiP_C=p_[7];
	double kf_cAMPxRii__Rii_cAMP=p_[8];
	double kb_cAMPxRii__Rii_cAMP=p_[9];
	double kf_Rii_CxcAMP__Rii_C_cAMP=p_[10];
	double kb_Rii_CxcAMP__Rii_C_cAMP=p_[11];
	double kf_RiixC__Rii_C=p_[12];
	double kf_Rii_cAMPxC__Rii_C_cAMP=p_[13];
	double kb_Rii_cAMPxC__Rii_C_cAMP=p_[14];
	double kf_Rii_C_cAMP__RiiP_C_cAMP=p_[15];
	double kb_RiixC__Rii_C=p_[16];
	double AKAPoff_1=p_[17];
	double AKAPoff_3=p_[18];
	double AKAPon_1=p_[19];
	double AKAPon_3=p_[20];
	double kf_C_AKAR4=p_[21];
	double kb_C_AKAR4=p_[22];
	double kcat_AKARp=p_[23];
	double kmOFF=p_[24];
	double kmON=p_[25];
	double KD_T=p_[26];
	double b_AKAP=p_[27];
	/* the initial value of y may depend on the parameters. */
	y_[0] = 6.3;
	y_[1] = 0;
	y_[2] = 0;
	y_[3] = 0.63;
	y_[4] = 0;
	y_[5] = 0;
	y_[6] = 0;
	y_[7] = 0;
	y_[8] = 0;
	y_[9] = 0;
	y_[10] = 1.5;
	y_[11] = 0;
	y_[12] = 0;
	y_[13] = 0.2;
	y_[14] = 0;
	y_[15] = 0;
	return GSL_SUCCESS;
}
