#!/usr/bin/env Rscript

library(SBtabVFGEN)
args <- commandArgs(TRUE)
conLawAnalysis <- any(c("--cla","-c","--conservation-law-analysis") %in% args)

if (length(args)>0){
    f <- file.exists(args)
    tsv <- grepl('.*[.]tsv$',args)
    ods <- grepl('.*[.]ods$',args)
    xlsx <- grepl('.*[.]xlsx$',args)
    model.tsv <- args[f & tsv]
    model.ods <- args[f & ods]
    model.xlsx <- args[f & xlsx]
} else {
    model.tsv<-dir(pattern='[.]tsv$')
    message('without any command line arguments, I will use all tsv file in this folder: ')
    message(sprintf("«%s»",model.tsv))
}

if (length(model.tsv) > 0){
	model.sbtab<-sbtab_from_tsv(model.tsv)
	sbtab_to_vfgen(model.sbtab,cla=conLawAnalysis)
}

if ((n<-length(model.ods)) > 0){
	for (i in seq(n)){
		model.sbtab<-sbtab_from_ods(model.ods[i])
		sbtab_to_vfgen(model.sbtab,cla=conLawAnalysis)
	}
}

if ((n<-length(model.xlsx)) > 0){
	for (i in seq(n)){
		model.sbtab<-sbtab_from_ods(model.xlsx[i])
		sbtab_to_vfgen(model.sbtab,cla=conLawAnalysis)
	}
}
