#
# AKAR4.R
#
# R vector field functions for: AKAR4
#
# This file was generated by the program VFGEN, version: 2.6.0.dev1
# Generated on  2-Mar-2022 at 17:01
#


#
# AKAR4(t, state, parameters)
#
# The vector field function
#
AKAR4 <- function(t, state, parameters) {
    AKAR4      <- state[1]
    AKAR4_C    <- state[2]
    AKAR4p     <- state[3]
    C          <- state[4]
    kf_C_AKAR4 <- parameters[1]
    kb_C_AKAR4 <- parameters[2]
    kcat_AKARp <- parameters[3]

    reaction_1 <- -kb_C_AKAR4*AKAR4_C+AKAR4*C*kf_C_AKAR4;
    reaction_2 <- kcat_AKARp*AKAR4_C;
    vf_ <- vector(len = 4)
    vf_[1] = -reaction_1;
    vf_[2] = reaction_1-reaction_2;
    vf_[3] = reaction_2;
    vf_[4] = -reaction_1+reaction_2;
    return(list(vf_))
}

#
# AKAR4_jac(t, state, parameters)
#
# The jacobian function
#
AKAR4_jac <- function(t, state, parameters) {
    AKAR4      <- state[1]
    AKAR4_C    <- state[2]
    AKAR4p     <- state[3]
    C          <- state[4]
    kf_C_AKAR4 <- parameters[1]
    kb_C_AKAR4 <- parameters[2]
    kcat_AKARp <- parameters[3]
    jac_ = matrix(nrow = 4, ncol = 4)
    jac_[1,1] = -C*kf_C_AKAR4
    jac_[1,2] = kb_C_AKAR4
    jac_[1,3] = 0
    jac_[1,4] = -AKAR4*kf_C_AKAR4
    jac_[2,1] = C*kf_C_AKAR4
    jac_[2,2] = -kb_C_AKAR4-kcat_AKARp
    jac_[2,3] = 0
    jac_[2,4] = AKAR4*kf_C_AKAR4
    jac_[3,1] = 0
    jac_[3,2] = kcat_AKARp
    jac_[3,3] = 0
    jac_[3,4] = 0
    jac_[4,1] = -C*kf_C_AKAR4
    jac_[4,2] = kb_C_AKAR4+kcat_AKARp
    jac_[4,3] = 0
    jac_[4,4] = -AKAR4*kf_C_AKAR4
    return(jac_)
}


#
# AKAR4_sol_AKAR4pOUT
#
# This function implements the user-defined function "AKAR4pOUT"
#
AKAR4_sol_AKAR4pOUT <- function(sol, parameters) {
    t <- sol[, 1]
    AKAR4      <- sol[, 2]
    AKAR4_C    <- sol[, 3]
    AKAR4p     <- sol[, 4]
    C          <- sol[, 5]
    kf_C_AKAR4 <- parameters[1]
    kb_C_AKAR4 <- parameters[2]
    kcat_AKARp <- parameters[3]
    reaction_1 <- -kb_C_AKAR4*AKAR4_C+AKAR4*C*kf_C_AKAR4
    reaction_2 <- kcat_AKARp*AKAR4_C
    r_ <- AKAR4p;
    return(r_)
}

#
# AKAR4_AKAR4pOUT
#
# This function implements the user-defined function "AKAR4pOUT"
#
AKAR4_AKAR4pOUT <- function(t, state, parameters) {
    AKAR4      <- state[1]
    AKAR4_C    <- state[2]
    AKAR4p     <- state[3]
    C          <- state[4]
    kf_C_AKAR4 <- parameters[1]
    kb_C_AKAR4 <- parameters[2]
    kcat_AKARp <- parameters[3]
    reaction_1 <- -kb_C_AKAR4*AKAR4_C+AKAR4*C*kf_C_AKAR4
    reaction_2 <- kcat_AKARp*AKAR4_C
    r_ <- AKAR4p;
    return(r_)
}
