/*
 *  AKAR4_gvf.h
 *
 *  GSL C prototype file for the functions defined in AKAR4_gvf.c
 *
 *  This file was generated by the program VFGEN, version: 2.6.0.dev1
 *  Generated on 25-Feb-2022 at 15:40
 */

int AKAR4_vf(double, const double [], double [], void *);
int AKAR4_jac(double, const double [], double *, double *, void *);
int AKAR4_jacp(double, const double [], double *, void *);
