/*
 *  CaMKIIs_cvs.h
 *
 *  CVODES C prototype file for the functions defined in CaMKIIs_cvs.c
 *
 *  This file was generated by the program VFGEN (Version:2.4.1)
 *  Generated on 15-Mar-2021 at 15:02
 */

int CaMKIIs_vf(realtype, N_Vector, N_Vector, void *);
int CaMKIIs_jac(long, realtype,
                N_Vector, N_Vector,
                DlsMat, void *,
                N_Vector, N_Vector, N_Vector);
int CaMKIIs_jacp(int, realtype,
                N_Vector, N_Vector,
                DlsMat, void *,
                N_Vector, N_Vector, N_Vector);
int CaMKIIs_sens(int, realtype, N_Vector, N_Vector,
                int, N_Vector, N_Vector,
                void *, N_Vector, N_Vector);
int CaMKIIs_func(realtype, N_Vector, realtype *, void *);
int CaMKIIs_func_sens(realtype, N_Vector, N_Vector *, double *, void *);
