test_that("simfi produces a solution for AKAR4",{
	f <- uqsa_example('AKAR4')
	expect_vector(f, ptype = character(0))
	m <- model_from_tsv(f)
	expect_type(m,"list")
	expect_equal(length(f),length(m))
	o <- as_ode(m,cla=FALSE)
	suppressMessages({
		ex <- experiments(m,o)
	})
	suppressWarnings({
		C <- generate_code(o)
	})
	expect_type(C,"character")
	c_path(o) <- write_c_code(C)
	so_path(o) <- shlib(o)
	s <- simfi(ex,o,parMap=log10ParMap)
	p <- log10(values(m$Parameter))
	expect_true(length(p)==NROW(m$Parameter))
	rprior <- rNormalPrior(mean=p,sd=rep_len(0.1,length(p)))
	N <- 10
	X <- rprior(N)
	y <- s(t(X))
	expect_equal(length(y),length(ex))
	expect_equal(dim(y[[1]]$state),c(NROW(m$Compound),length(ex[[1]]$outputTimes),N))
	expect_false(is.null(y[[1]]$FisherInformation))
	expect_false(is.null(y[[1]]$gradLogLikelihood))
	expect_false(is.null(y[[1]]$logLikelihood))
	expect_false(is.null(y[[1]]$func))
	expect_false(is.null(y[[1]]$state))
})

test_that("simfi produces a solution for AKAR4, without Fisher Information",{
	f <- uqsa_example('AKAR4')
	expect_vector(f, ptype = character(0))
	m <- model_from_tsv(f)
	expect_type(m,"list")
	expect_equal(length(f),length(m))
	o <- as_ode(m,cla=FALSE)
	suppressMessages({
		ex <- experiments(m,o)
	})
	suppressWarnings({
		C <- generate_code(o)
	})
	expect_type(C,"character")
	c_path(o) <- write_c_code(C)
	so_path(o) <- shlib(o)
	s <- simfi(ex,o,parMap=log10ParMap,omit=1)
	p <- log10(values(m$Parameter))
	expect_true(length(p)==NROW(m$Parameter))
	#expect_vector(p, ptype = numeric(0), size=NROW(m$Parameter))
	rprior <- rNormalPrior(mean=p,sd=rep_len(0.1,length(p)))
	N <- 10
	X <- rprior(N)
	y <- s(t(X))
	expect_equal(length(y),length(ex))
	expect_equal(dim(y[[1]]$state),c(NROW(m$Compound),length(ex[[1]]$outputTimes),N))
	expect_true(is.null(y[[1]]$FisherInformation))
	expect_false(is.null(y[[1]]$gradLogLikelihood))
	expect_false(is.null(y[[1]]$logLikelihood))
	expect_false(is.null(y[[1]]$func))
	expect_false(is.null(y[[1]]$state))
})

test_that("simfi produces a solution for AKAR4, without Fisher Information, and gradient of log-likelihood",{
	f <- uqsa_example('AKAR4')
	expect_vector(f, ptype = character(0))
	m <- model_from_tsv(f)
	expect_type(m,"list")
	expect_equal(length(f),length(m))
	o <- as_ode(m,cla=FALSE)
	suppressMessages({
		ex <- experiments(m,o)
	})
	suppressWarnings({
		C <- generate_code(o)
	})
	expect_type(C,"character")
	c_path(o) <- write_c_code(C)
	so_path(o) <- shlib(o)
	s <- simfi(ex,o,parMap=log10ParMap,omit=2)
	p <- log10(values(m$Parameter))
	expect_true(length(p)==NROW(m$Parameter))
#	expect_vector(p, ptype = numeric(0), size=NROW(m$Parameter))
	rprior <- rNormalPrior(mean=p,sd=rep_len(0.1,length(p)))
	N <- 10
	X <- rprior(N)
	y <- s(t(X))
	expect_equal(length(y),length(ex))
	expect_equal(dim(y[[1]]$state),c(NROW(m$Compound),length(ex[[1]]$outputTimes),N))
	expect_true(is.null(y[[1]]$FisherInformation))
	expect_true(is.null(y[[1]]$gradLogLikelihood))
	expect_false(is.null(y[[1]]$logLikelihood))
	expect_false(is.null(y[[1]]$func))
	expect_false(is.null(y[[1]]$state))
})

test_that("simfi produces a solution for AKAR4, omit all optionals",{
	f <- uqsa_example('AKAR4')
	expect_vector(f, ptype = character(0))
	m <- model_from_tsv(f)
	expect_type(m,"list")
	expect_equal(length(f),length(m))
	suppressMessages({
		o <- as_ode(m,cla=FALSE)
	})
	suppressMessages({
		ex <- experiments(m,o)
	})
	suppressWarnings({
		C <- generate_code(o)
	})
	expect_type(C,"character")
	c_path(o) <- write_c_code(C)
	so_path(o) <- shlib(o)
	s <- simfi(ex,o,parMap=log10ParMap,omit=3)
	p <- log10(values(m$Parameter))
	expect_true(length(p)==NROW(m$Parameter))
#	expect_vector(p, ptype = numeric(0), size=NROW(m$Parameter))
	rprior <- rNormalPrior(mean=p,sd=rep_len(0.1,length(p)))
	N <- 10
	X <- rprior(N)
	y <- s(t(X))
	expect_equal(length(y),length(ex))
	expect_equal(dim(y[[1]]$state),c(NROW(m$Compound),NCOL(ex[[1]]$data),N))
	expect_true(is.null(y[[1]]$FisherInformation))
	expect_true(is.null(y[[1]]$gradLogLikelihood))
	expect_true(is.null(y[[1]]$logLikelihood))
	expect_false(is.null(y[[1]]$func))
	expect_false(is.null(y[[1]]$state))
})
